import {getIcon} from './icons.js';
export function studioLiveCSS(){return `
 .gamma-live-panel { position:fixed; z-index:330; right:96px; bottom:80px; width:360px; max-width:calc(100vw - 32px); max-height:calc(100dvh - 112px); overflow:auto; box-sizing:border-box; padding:24px; border:1px solid var(--studio-line); border-radius:16px; background:var(--studio-panel); color:var(--studio-ink); font:500 14px/1.5 Archivo,sans-serif; }
 .gamma-live-panel[hidden] { display:none; }.gamma-live-panel header { display:flex; align-items:center; justify-content:space-between; gap:16px; margin-bottom:16px; }.gamma-live-panel h2 { margin:0; font:600 24px/1.2 Archivo,sans-serif; color:var(--studio-ink); }
 .gamma-live-panel button,.gamma-live-panel select { min-height:44px; border:1px solid var(--studio-line); border-radius:9px; padding:8px 12px; background:var(--studio-panel-raised); color:var(--studio-ink); font:500 14px/1.4 Archivo,sans-serif; cursor:pointer; }.gamma-live-panel header button { width:44px; padding:10px; }.gamma-live-panel svg { display:block; width:20px; height:20px; }
 .gamma-live-panel button:focus-visible,.gamma-live-panel select:focus-visible,.gamma-camera button:focus-visible { outline:2px solid var(--studio-blue-soft); outline-offset:3px; }
 .gamma-live-panel button[aria-pressed=true] { border-color:var(--studio-green); color:var(--studio-green); }.gamma-live-panel button:disabled { opacity:.5; cursor:default; }
 .gamma-live-status { color:var(--studio-muted); margin:0 0 20px; }.gamma-live-media { display:grid; grid-template-columns:1fr 1fr; gap:12px; }
 .gamma-live-panel label { display:flex; flex-direction:column; gap:8px; margin-top:16px; color:var(--studio-muted); }.gamma-live-panel select { width:100%; min-width:0; font-size:16px; }
 .gamma-live-panel .gamma-live-primary { width:100%; margin-top:12px; background:var(--studio-blue); border-color:var(--studio-blue); color:var(--studio-ink); }.gamma-live-secondary { display:flex; flex-wrap:wrap; gap:8px; margin-top:16px; padding-top:16px; border-top:1px solid var(--studio-line); }
 .gamma-live-panel details {border-top:1px solid var(--studio-line);margin-top:12px}.gamma-live-panel summary {min-height:44px;display:flex;align-items:center;cursor:pointer;color:var(--studio-ink)}.gamma-live-panel details>button {margin-top:16px}.gamma-live-note { color:var(--studio-muted); font-size:12px; margin:12px 0; }.gamma-live-take { margin-top:20px; padding-top:16px; border-top:1px solid var(--studio-line); }.gamma-live-take p { overflow-wrap:anywhere; margin:0 0 8px; }
 .gamma-recording-badge { left:50%; right:auto; bottom:12px; transform:translateX(-50%); max-width:calc(100vw - 24px); min-height:44px; flex-wrap:wrap; justify-content:center; gap:8px; z-index:340; }.gamma-recording-badge button { min-height:44px; padding:8px 12px; font-size:14px; }.gamma-recording-badge span { font-size:12px; }.gamma-recording-badge b { font-size:14px; }
 .gamma-camera { left:24px; right:auto; top:80px; bottom:auto; resize:none; min-width:140px; min-height:100px; max-width:calc(100vw - 32px); max-height:calc(100dvh - 160px); width:240px; aspect-ratio:16/10; }
 .gamma-camera .gamma-camera-label { min-height:44px; touch-action:none; cursor:move; }.gamma-camera-resize { position:absolute; right:0; bottom:0; width:44px; height:44px; border:0; background:var(--studio-panel); color:var(--studio-ink); cursor:nwse-resize; touch-action:none; border-radius:9px 0 0 0; display:grid; place-items:center; }.gamma-camera-resize svg { width:20px; height:20px; }
 .gamma-countdown button { min-height:44px; padding:12px 24px; font:500 16px Archivo,sans-serif; color:var(--studio-ink); background:var(--studio-panel); border:1px solid var(--studio-line); border-radius:9px; }.gamma-countdown.is-visible { grid-template-rows:auto auto; align-content:center; gap:32px; }
 html.gamma-studio-modal-open .gamma-live-panel,body:has(.gamma-recording-review.is-visible) .gamma-live-panel { visibility:hidden; }
 @media(max-width:900px) { .gamma-live-panel { right:16px; bottom:188px; max-height:calc(100dvh - 220px); padding:20px; }.gamma-camera { left:16px; top:72px; right:auto; bottom:auto; width:190px; }.gamma-recording-badge { bottom:8px; width:calc(100vw - 24px); box-sizing:border-box; }.gamma-recording-badge .gamma-record-state { display:none; } }
 @media print { .gamma-live-panel { display:none!important; } }html.gamma-export .gamma-live-panel { display:none; }
`;}
function initStudioLive(icons){
 if(new URLSearchParams(location.search).has('gamma-clean')||new URLSearchParams(location.search).has('gamma-export')||new URLSearchParams(location.search).has('print-pdf'))return;
 const panel=document.createElement('section');panel.className='gamma-live-panel';panel.hidden=true;panel.setAttribute('aria-label','Presentation Studio');
 panel.innerHTML="<header><h2>Studio</h2><button data-live=\"close\" aria-label=\"Close Studio\">"+icons.close+"</button></header><p class=\"gamma-live-status\" role=\"status\"></p><div class=\"gamma-live-media\"><button data-live=\"camera\" aria-pressed=\"false\">Camera</button><button data-live=\"microphone\" aria-pressed=\"false\">Microphone</button></div><button class=\"gamma-live-primary\" data-live=\"output-window\">1 \u00b7 Open video output</button><button class=\"gamma-live-primary\" data-live=\"source\">2 \u00b7 Choose source</button><button class=\"gamma-live-primary\" data-live=\"record\">3 \u00b7 Record</button><p class=\"gamma-live-note\" data-live-support></p><details><summary>Composition and sources</summary><label>Source to record<select data-live-setting=\"captureMode\"><option value=\"clean\">Clean output</option><option value=\"presentation\">Raw capture</option><option value=\"external\">External source</option></select></label><label>Video format<select data-live-setting=\"output\"><option value=\"source\">Source dimensions</option><option value=\"landscape\">YouTube \u00b7 1920 \u00d7 1080</option><option value=\"portrait\">Vertical \u00b7 1080 \u00d7 1920</option><option value=\"square\">Square \u00b7 1080 \u00d7 1080</option></select></label><label>Camera position<select data-live-camera-position><option value=\"tl\">Top left</option><option value=\"tr\">Top right</option><option value=\"bl\">Bottom left</option><option value=\"br\">Bottom right</option></select></label><label>Camera size<select data-live-camera-size><option value=\"190\">Small</option><option value=\"280\">Medium</option><option value=\"380\">Large</option></select></label><button data-live=\"configure\">Choose devices</button></details><details><summary>Demonstrations</summary><div class=\"gamma-live-secondary\"><button data-live=\"browser\">Open browser</button><button data-live=\"terminal\">Open terminal</button></div><label>Include in video<select data-live-broadcast><option value=\"slides\">Slides</option><option value=\"terminal\">Terminal</option><option value=\"browser\">Browser</option></select></label><p class=\"gamma-live-note\">Opening a tool does not broadcast it. Choose its content explicitly here.</p></details><div class=\"gamma-live-take\" hidden><p></p><button data-live=\"review\">Review take</button></div>";
 document.body.append(panel);let api;
 const busy=phase=>['starting','countdown','recording','paused','finalizing'].includes(phase);
 function update(){if(!window.__gammaStudio)return;api=window.__gammaStudio;const s=api.snapshot();panel.querySelector('.gamma-live-status').textContent=({recording:'Recording in progress',paused:'Recording paused',starting:'Preparing take',finalizing:'Finalizing video'}[s.phase]||'Ready to present');for(const key of ['camera','microphone']){const b=panel.querySelector('[data-live='+key+']');b.setAttribute('aria-pressed',String(s[key]));b.textContent=key==='camera'?(s.camera?'Camera visible':'Camera hidden'):(s.microphone?'Microphone enabled':'Microphone muted');b.disabled=!s.mediaSupported;}
 panel.querySelectorAll('select[data-live-setting]').forEach(el=>{el.value=s[el.dataset.liveSetting];el.disabled=busy(s.phase);});panel.querySelector('[data-live=source]').disabled=busy(s.phase)||!s.screenSupported;panel.querySelector('[data-live=source]').textContent=s.screen?'Source ready · change':'Choose screen or tab';panel.querySelector('[data-live=record]').disabled=busy(s.phase)||!s.screen||!!s.lastRecording&&!s.lastRecording.saved;panel.querySelector('[data-live=configure]').disabled=busy(s.phase);
 const outputReady=!!window.__gammaOutputWindow&&!window.__gammaOutputWindow.closed;panel.querySelector('[data-live=output-window]').hidden=s.captureMode!=='clean'||outputReady;panel.querySelector('[data-live=source]').hidden=s.screen||s.captureMode==='clean'&&!outputReady;panel.querySelector('[data-live=record]').hidden=!s.screen||busy(s.phase);
 panel.querySelector('[data-live-support]').textContent=s.screenSupported?(s.captureMode==='clean'?'Open video output, then share that tab. Menus and controls stay out of frame. Source format avoids bars.':s.captureMode==='presentation'?'Raw capture: visible menus and controls will be recorded.':'The external source will be recorded with your camera. Studio controls stay in this window.'):'This browser does not support screen capture. Use the phone system recorder; camera, content, and controls remain available.';
 panel.querySelector('[data-live-broadcast] option[value=browser]').disabled=window.__gammaBrowserMode!=='local';
 const take=panel.querySelector('.gamma-live-take');take.hidden=!s.lastRecording;if(s.lastRecording)take.querySelector('p').textContent=(s.lastRecording.saved?'Take saved':'Take retained · save to verify')+(s.lastRecording.dimensions?' · '+s.lastRecording.dimensions.join(' × '):'');
 document.querySelectorAll('[data-action=live-mic]').forEach(b=>{b.textContent=s.microphone?'Mute microphone':'Enable microphone';b.setAttribute('aria-pressed',String(s.microphone));});document.querySelectorAll('[data-action=live-camera]').forEach(b=>{b.textContent=s.camera?'Hide camera':'Show camera';b.setAttribute('aria-pressed',String(s.camera));});
 }
 function install(){initPresenterStudio();api=window.__gammaStudio;const camera=document.querySelector('.gamma-camera');if(!camera||camera.dataset.liveReady)return;camera.dataset.liveReady='true';const drag=camera.querySelector('[data-testid=studio-camera-drag]');drag.tabIndex=0;drag.setAttribute('role','button');drag.setAttribute('aria-label','Move camera with arrow keys');
 const clamp=()=>{if(!camera.classList.contains('is-visible'))return;const r=camera.getBoundingClientRect();camera.style.width=Math.min(r.width,innerWidth-32)+'px';camera.style.height=Math.min(r.height,innerHeight-160)+'px';camera.style.left=Math.max(8,Math.min(innerWidth-camera.offsetWidth-8,r.left))+'px';camera.style.top=Math.max(8,Math.min(innerHeight-camera.offsetHeight-80,r.top))+'px';camera.style.right='auto';camera.style.bottom='auto';};
 drag.addEventListener('keydown',e=>{if(!e.key.startsWith('Arrow'))return;e.preventDefault();e.stopPropagation();const r=camera.getBoundingClientRect();camera.style.left=r.left+(e.key==='ArrowRight'?16:e.key==='ArrowLeft'?-16:0)+'px';camera.style.top=r.top+(e.key==='ArrowDown'?16:e.key==='ArrowUp'?-16:0)+'px';clamp();});
 const resize=document.createElement('button');resize.className='gamma-camera-resize';resize.setAttribute('aria-label','Resize camera');resize.innerHTML=icons.resize;camera.append(resize);
 const size=(w,h)=>{camera.style.width=Math.max(140,Math.min(innerWidth-32,w))+'px';camera.style.height=Math.max(100,Math.min(innerHeight-160,h))+'px';camera.style.aspectRatio='auto';clamp();};
 resize.addEventListener('pointerdown',e=>{e.preventDefault();const r=camera.getBoundingClientRect(),x=e.clientX,y=e.clientY;resize.setPointerCapture(e.pointerId);const move=p=>size(r.width+p.clientX-x,r.height+p.clientY-y),end=()=>{resize.removeEventListener('pointermove',move);resize.removeEventListener('pointerup',end);resize.removeEventListener('pointercancel',end);};resize.addEventListener('pointermove',move);resize.addEventListener('pointerup',end);resize.addEventListener('pointercancel',end);});
 resize.addEventListener('keydown',e=>{if(!e.key.startsWith('Arrow'))return;e.preventDefault();e.stopPropagation();const r=camera.getBoundingClientRect();size(r.width+(e.key==='ArrowRight'?16:e.key==='ArrowLeft'?-16:0),r.height+(e.key==='ArrowDown'?16:e.key==='ArrowUp'?-16:0));});window.addEventListener('resize',clamp);
 panel.querySelector('[data-live-camera-position]').addEventListener('change',e=>{const r=camera.getBoundingClientRect();camera.style.left=(e.target.value.endsWith('l')?16:innerWidth-r.width-96)+'px';camera.style.top=(e.target.value.startsWith('t')?80:innerHeight-r.height-160)+'px';clamp();});panel.querySelector('[data-live-camera-size]').addEventListener('change',e=>size(+e.target.value,+e.target.value*.625));
 const transport=document.querySelector('.gamma-recording-badge');for(const [key,label] of [['mic','Microphone'],['camera','Camera']]){const b=document.createElement('button');b.dataset.action='live-'+key;b.textContent=label;b.addEventListener('click',()=>Promise.resolve(api[key==='mic'?'microphone':'camera']()).then(update));transport.insertBefore(b,transport.querySelector('[data-action=stop-recording]'));}
 }
 window.addEventListener('gamma:studio-open',()=>{install();panel.hidden=!panel.hidden;update();if(!panel.hidden)panel.querySelector('[data-live=close]').focus();});window.addEventListener('gamma:studio-state',update);
 panel.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Escape'){panel.hidden=true;document.querySelector('.gamma-orbit-hub')?.focus();}});
 panel.addEventListener('click',async e=>{const action=e.target.closest('[data-live]')?.dataset.live;if(!action)return;if(action==='output-window'){if(!window.__gammaOpenOutput?.())panel.querySelector('[data-live-support]').textContent='Allow the output window, then try again.';update();return;}if(action==='close'){panel.hidden=true;document.querySelector('.gamma-orbit-hub')?.focus();return;}if(action==='terminal'||action==='browser'){panel.hidden=true;window.dispatchEvent(new Event(action==='terminal'?'gamma:terminal-request':'gamma:browser-open'));return;}if(action==='record')panel.hidden=true;await api[action]?.();update();});
 panel.querySelector('[data-live-broadcast]').addEventListener('change',e=>{window.__gammaOutputFlags.terminal=e.target.value==='terminal';window.__gammaOutputFlags.browser=e.target.value==='browser';});
 panel.querySelectorAll('[data-live-setting]').forEach(el=>el.addEventListener('change',()=>{api[el.dataset.liveSetting==='output'?'setOutput':'setCaptureMode'](el.value);update();}));
 window.addEventListener('gamma:archify-fullscreen',()=>{const host=document.querySelector('.archify-fullscreen[open]')||document.body;for(const node of document.querySelectorAll('.gamma-camera,.gamma-recording-badge')){if(host.moveBefore)host.moveBefore(node,null);else{host.append(node);node.querySelector('video')?.play().catch(()=>{});}}});
 install();update();
}
export function studioLiveJS(){return `(${initStudioLive.toString()})(${JSON.stringify({close:getIcon('close'),resize:getIcon('expand')})});`;}
