/** The audience window contains the presentation only. Operator controls never enter it. */
export function studioOutputCSS(){return `
html.gamma-clean-stage .gamma-orbit,html.gamma-clean-stage .gamma-studio-toolbar,html.gamma-clean-stage .gamma-progress-hud,html.gamma-clean-stage .gamma-recording-badge,html.gamma-clean-stage .gamma-studio-notice,html.gamma-clean-stage .gamma-theme-switcher,html.gamma-clean-stage .gamma-theme-chooser,html.gamma-clean-stage .gamma-studio-overlay,html.gamma-clean-stage .experience-tools,html.gamma-clean-stage .experience-nav,html.gamma-clean-stage .experience-mobile-scroll,html.gamma-clean-stage .experience-more,html.gamma-clean-stage .controls,html.gamma-clean-stage .slide-number,html.gamma-clean-stage .progress,html.gamma-clean-stage .gamma-live-panel,html.gamma-clean-stage .gamma-terminal,html.gamma-clean-stage .gamma-terminal-restore,html.gamma-clean-stage .archify-controls,html.gamma-clean-stage .archify-reading>label,html.gamma-clean-stage .archify-data,html.gamma-clean-stage .d3-webgpu-actions,html.gamma-clean-stage .d3-depth-toolbar,html.gamma-clean-stage .spatial-toolbar,html.gamma-clean-stage .cinema-actions,html.gamma-clean-stage .cinema-tools,html.gamma-clean-stage .studio-slide-actions,html.gamma-clean-stage .d3-webgpu-readout[hidden],html.gamma-clean-stage .gamma-operator-only,html.gamma-clean-stage .experience-start,html.gamma-clean-stage .experience-chapter-map a>span,html.gamma-clean-stage .experience-chapter-map a>svg,html.gamma-clean-stage .cinema-data>button,html.gamma-clean-stage .d3-webgpu-data [data-d3-action=close],html.gamma-clean-stage .archify-close,html.gamma-clean-stage .chart-scenario-legend button{display:none!important}
.gamma-output-camera{position:fixed;z-index:400;object-fit:cover;transform:scaleX(-1);border-radius:16px;pointer-events:none}.gamma-output-camera[hidden],.gamma-output-demo[hidden]{display:none}.gamma-output-demo{position:fixed;inset:5vh 5vw;width:90vw;height:90vh;z-index:350;background:var(--studio-panel);color:var(--studio-ink);border:1px solid var(--studio-line);border-radius:16px;box-sizing:border-box;overflow:auto;margin:0;object-fit:contain;font:500 16px/1.6 Azeret Mono,monospace;padding:24px}.gamma-output-demo img,.gamma-output-demo video{width:100%;height:100%;object-fit:contain}
`;}
function initStudioOutput(){
 const params=new URLSearchParams(location.search),clean=params.get('gamma-clean');
 if(clean){
  window.__gammaBroadcastActive=true;document.documentElement.classList.add('gamma-clean-stage');document.title='SORTIE VIDÉO · '+document.title;
  try{navigator.mediaDevices?.setCaptureHandleConfig?.({handle:'gamma-clean-'+clean,exposeOrigin:true,permittedOrigins:[location.origin]});}catch{}
  const camera=document.createElement('video');camera.className='gamma-output-camera';camera.muted=true;camera.autoplay=true;camera.playsInline=true;camera.hidden=true;document.body.append(camera);
  const terminal=document.createElement('pre');terminal.className='gamma-output-demo';terminal.hidden=true;document.body.append(terminal);const browser=document.createElement('div');browser.className='gamma-output-demo';browser.hidden=true;const browserVideo=document.createElement('video');browserVideo.autoplay=true;browserVideo.playsInline=true;browserVideo.muted=true;browserVideo.setAttribute('aria-label','Démonstration du navigateur');browser.append(browserVideo);document.body.append(browser);
  window.addEventListener('gamma:archify-fullscreen',()=>{const host=document.querySelector('.archify-fullscreen[open]')||document.body;for(const node of [camera,terminal,browser]){if(host.moveBefore)host.moveBefore(node,null);else host.append(node);}});
  const mirrors=new Map();
  function mirrorRenders(){
   const source=opener?.Reveal?.getCurrentSlide(),target=Reveal.getCurrentSlide();if(!source||!target)return;
   for(const [node,m] of mirrors)if(!source.contains(node)||!target.contains(m.target)){m.stream?.getTracks().forEach(t=>t.stop());m.dispose?.();m.video?.remove();m.target.style.visibility='';m.hiddenSVG?.forEach(([svg,visibility])=>svg.style.visibility=visibility);mirrors.delete(node);}
   const destinations=[...target.querySelectorAll('canvas:not(.gamma-output-canvas)')];source.querySelectorAll('canvas').forEach((node,i)=>{const dest=destinations[i];if(!dest||mirrors.has(node)||!node.width||!node.height||!node.getBoundingClientRect().width||getComputedStyle(node).visibility==='hidden')return;try{const video=document.createElement('canvas');video.className='gamma-output-canvas';video.width=node.width;video.height=node.height;const context=video.getContext('2d',{alpha:false});video.style.cssText='position:absolute;pointer-events:none;z-index:2;object-fit:fill;';dest.parentElement.style.position='relative';dest.parentElement.append(video);dest.style.visibility='hidden';const hiddenSVG=[...dest.parentElement.querySelectorAll(':scope>svg')].map(svg=>[svg,svg.style.visibility]);hiddenSVG.forEach(([svg])=>svg.style.visibility='hidden');let frame=0,stopped=false,last=0;const copy=now=>{if(stopped)return;if(now-last>=30){last=now;if(video.width!==node.width)video.width=node.width;if(video.height!==node.height)video.height=node.height;context.fillStyle=getComputedStyle(document.body).backgroundColor;context.fillRect(0,0,video.width,video.height);try{context.drawImage(node,0,0);}catch{video.hidden=true;dest.style.visibility='';hiddenSVG.forEach(([svg,visibility])=>svg.style.visibility=visibility);stopped=true;return;}}frame=window.__gammaFrame(copy);};mirrors.set(node,{target:dest,video,hiddenSVG,dispose:()=>{stopped=true;window.__gammaCancelFrame(frame);}});frame=window.__gammaFrame(copy);opener.dispatchEvent(new Event('resize'));}catch{}});
   for(const m of mirrors.values())if(m.video){m.video.style.left=m.target.offsetLeft+'px';m.video.style.top=m.target.offsetTop+'px';m.video.style.width=m.target.clientWidth+'px';m.video.style.height=m.target.clientHeight+'px';}
   source.querySelectorAll('[id^=chart_]').forEach(chart=>{const dest=target.querySelector('[id="'+chart.id+'"]');if(!dest)return;const tip=[...chart.children].find(el=>el.tagName==='DIV'&&getComputedStyle(el).position==='absolute'&&Number(getComputedStyle(el).zIndex)>=100);let copy=dest.querySelector(':scope>.gamma-output-tooltip');if(!tip){copy?.remove();return;}if(!copy){copy=document.createElement('div');copy.className='gamma-output-tooltip';dest.append(copy);}copy.innerHTML=tip.innerHTML;copy.style.cssText=tip.style.cssText;const a=chart.getBoundingClientRect(),r=tip.getBoundingClientRect();copy.style.transform='none';copy.style.left=(r.left-a.left)/a.width*dest.clientWidth+'px';copy.style.top=(r.top-a.top)/a.height*dest.clientHeight+'px';});
   source.querySelectorAll('[id^=chart_] svg').forEach(svg=>{if(!svg.getBoundingClientRect().width||getComputedStyle(svg).visibility==='hidden')return;const id=svg.closest('[id^=chart_]').id,dest=target.querySelector('[id="'+id+'"]');if(!dest)return;let overlay=dest.querySelector(':scope>.gamma-output-chart');if(!overlay){overlay=document.createElement('div');overlay.className='gamma-output-chart';overlay.style.cssText='position:absolute;inset:0;z-index:3;pointer-events:none';dest.style.position='relative';dest.append(overlay);}dest.querySelectorAll('svg').forEach(original=>{if(!original.closest('.gamma-output-chart'))original.style.visibility='hidden';});const markup=svg.outerHTML;if(overlay.__markup!==markup){overlay.innerHTML=markup;overlay.__markup=markup;const copy=overlay.querySelector('svg');copy.setAttribute('viewBox','0 0 '+svg.getAttribute('width')+' '+svg.getAttribute('height'));copy.style.width='100%';copy.style.height='100%';}});
  }
  const receive=e=>{if(e.source!==opener||e.data?.channel!=='gamma-output'||e.data.key!==clean)return;const d=e.data;
   if(d.kind==='state'){
    const current=Reveal.getIndices();if(current.h!==d.slide.h||current.v!==d.slide.v||current.f!==d.slide.f)Reveal.slide(d.slide.h,d.slide.v,d.slide.f);
    if(d.theme&&document.body.dataset.presentationTheme!==d.theme&&typeof applyPresentationTheme==='function')applyPresentationTheme(d.theme,{animate:false});
    const section=Reveal.getCurrentSlide();if(section)section.scrollTop=d.scroll;const sourceReadout=opener?.document.querySelector('section.present .d3-webgpu-readout'),readout=section?.querySelector('.d3-webgpu-readout');if(sourceReadout&&readout){readout.textContent=sourceReadout.textContent;readout.hidden=sourceReadout.textContent===sourceReadout.dataset.defaultHint;}mirrorRenders();const full=document.querySelector('.archify-fullscreen[open]');if(d.full&&!full)section?.querySelector('[data-archify-action=fullscreen]')?.click();if(!d.full&&full)full.querySelector('[data-archify-action=close]')?.click();
    const mainCamera=opener?.document.querySelector('.gamma-camera video'),stream=mainCamera?.srcObject;camera.hidden=!d.camera?.visible;if(stream&&camera.srcObject!==stream){camera.srcObject=stream;camera.play().catch(()=>{});}if(d.camera){camera.style.left=d.camera.x*innerWidth+'px';camera.style.top=d.camera.y*innerHeight+'px';camera.style.width=d.camera.w*innerWidth+'px';camera.style.height=d.camera.h*innerHeight+'px';}
    terminal.hidden=!d.terminal?.visible;if(!terminal.hidden&&terminal.textContent!==d.terminal.text)terminal.textContent=d.terminal.text;
    browser.hidden=!d.browser?.visible;
    const browserStream=opener?.__gammaBrowserStream;
    if(!browser.hidden&&browserStream){if(browserVideo.srcObject!==browserStream)browserVideo.srcObject=browserStream;browserVideo.muted=!!d.browser.muted;if(browserVideo.paused)browserVideo.play().catch(()=>opener.__gammaOutputAudioBlocked=true);}
    else{browserVideo.pause();browserVideo.srcObject=null;browserVideo.muted=true;}

    const source=opener?.document.querySelector('section.present .studio-slide-media'),target=section?.querySelector('.studio-slide-media');if(source&&target){target.controls=false;target.muted=source.dataset.userMuted==='true';target.volume=source.volume;if(Math.abs(target.currentTime-source.currentTime)>.4)target.currentTime=source.currentTime;if(source.paused)target.pause();else target.play().catch(()=>{});}
   }else if(d.kind==='event'){
    let node=document;for(const i of d.path)node=node?.children?.[i];if(!node)return;const r=node.getBoundingClientRect();if(d.type==='change'){node.value=d.value;node.dispatchEvent(new Event('change',{bubbles:true}));}else if(d.type==='click')node.click?.();else{const C=d.type==='wheel'?WheelEvent:PointerEvent;node.dispatchEvent(new C(d.type,{bubbles:true,cancelable:true,clientX:r.left+d.x*r.width,clientY:r.top+d.y*r.height,pointerId:1,pointerType:'mouse',buttons:d.buttons,button:d.button,deltaY:d.deltaY}));}
   }else if(d.kind==='archify'){const state=window.__gammaArchify?.states.find(s=>s.section===Reveal.getCurrentSlide());if(state?.frame&&d.svg)state.frame.contentWindow.postMessage({channel:'gamma-archify',action:'snapshot',value:d.svg},'*');}else if(d.kind==='theme'&&typeof applyPresentationTheme==='function')applyPresentationTheme(d.theme,{animate:false});
  };window.addEventListener('message',receive);window.__gammaResumeOutputAudio=()=>Promise.all([...document.querySelectorAll('video,audio')].filter(m=>!m.muted&&m.srcObject||m.matches('section.present .studio-slide-media')).map(m=>m.play())).then(()=>opener.__gammaOutputAudioBlocked=false);return;
 }
 const mediaStates=new Map();const restoreAudio=()=>{for(const [m,muted] of mediaStates)m.muted=m.dataset.userMuted!==undefined?m.dataset.userMuted==='true':muted;mediaStates.clear();};
 let audience;const key=Math.random().toString(36).slice(2);window.__gammaCleanHandle='gamma-clean-'+key;window.__gammaOutputFlags={terminal:false,browser:false};
 const send=data=>{if(audience&&!audience.closed)audience.postMessage({channel:'gamma-output',key,...data},location.origin==='null'?'*':location.origin);};
 window.__gammaResizeOutput=profile=>{if(!audience||audience.closed)return;const [w,h]=profile==='portrait'?[1080,1920]:profile==='square'?[1080,1080]:profile==='landscape'?[1920,1080]:[1280,720];audience.resizeTo(w+audience.outerWidth-audience.innerWidth,h+audience.outerHeight-audience.innerHeight);};
 window.__gammaOpenOutput=()=>{const url=new URL(location.href);url.searchParams.set('gamma-clean',key);url.searchParams.set('theme',document.body.dataset.presentationTheme||'signal-room');const profile=window.__gammaStudio?.snapshot().output||'source',size=profile==='portrait'?'width=1080,height=1920':profile==='square'?'width=1080,height=1080':profile==='landscape'?'width=1920,height=1080':'width=1280,height=720';audience=window.open(url.href,'gamma-output-'+key,'popup,'+size);window.__gammaOutputWindow=audience;window.__gammaBroadcastActive=!!audience;document.dispatchEvent(new Event('visibilitychange'));return !!audience;};
 setInterval(()=>{if(!audience||audience.closed){restoreAudio();if(window.__gammaBroadcastActive){window.__gammaBroadcastActive=false;document.dispatchEvent(new Event('visibilitychange'));}return;}if(!audience.__GAMMA_READY__)return;for(const media of document.querySelectorAll('.studio-slide-media')){if(!mediaStates.has(media)){mediaStates.set(media,media.muted);media.dataset.userMuted ||= String(media.muted);}media.muted=true;}const browserMedia=document.querySelector('.gamma-browser video');if(browserMedia){if(!mediaStates.has(browserMedia))mediaStates.set(browserMedia,browserMedia.muted);browserMedia.muted=window.__gammaOutputFlags.browser?true:browserMedia.dataset.userMuted!=='false';}for(const state of window.__gammaArchify?.states||[]){if(state.frame&&state.root.dataset.ready==='true'&&!state.frame.dataset.broadcast){state.frame.dataset.broadcast='true';state.frame.contentWindow.postMessage({channel:'gamma-archify',action:'broadcast',value:true},'*');}}const cam=document.querySelector('.gamma-camera'),r=cam?.getBoundingClientRect(),term=document.querySelector('.gamma-terminal'),web=document.querySelector('.gamma-browser');send({kind:'state',full:!!document.querySelector('.archify-fullscreen[open]'),theme:document.body.dataset.presentationTheme,slide:Reveal.getIndices(),scroll:Reveal.getCurrentSlide()?.scrollTop||0,camera:r?{visible:cam.classList.contains('is-visible'),x:r.left/innerWidth,y:r.top/innerHeight,w:r.width/innerWidth,h:r.height/innerHeight}:null,terminal:{visible:window.__gammaOutputFlags.terminal&&term?.classList.contains('is-visible'),text:term?.querySelector('.gamma-terminal-output')?.innerText||''},browser:{visible:window.__gammaOutputFlags.browser&&web&&!web.hidden,muted:web?.querySelector('video')?.dataset.userMuted!=='false'}});},100);
 const pathTo=node=>{const path=[];while(node&&node!==document){path.unshift([...node.parentNode.children].indexOf(node));node=node.parentNode;}return path;};
 for(const type of ['click','change'])document.addEventListener(type,e=>{if(!audience||audience.closed||!e.target.closest('.reveal')||e.target.closest('[data-archify-action=fullscreen],[data-archify-action=close]'))return;const r=e.target.getBoundingClientRect();send({kind:'event',type,path:pathTo(e.target),x:(e.clientX-r.left)/(r.width||1),y:(e.clientY-r.top)/(r.height||1),buttons:e.buttons,button:e.button,deltaY:e.deltaY,value:e.target.value});},true);
 window.addEventListener('message',e=>{if(e.data?.channel==='gamma-archify'&&e.data.event==='state'&&window.__gammaArchify?.states.some(s=>s.frame?.contentWindow===e.source))send({kind:'archify',view:e.data.view,node:e.data.node,camera:e.data.camera,playing:e.data.playing,svg:e.data.svg});});
 window.addEventListener('gamma:theme-changed',e=>send({kind:'theme',theme:e.detail?.id||e.detail?.theme}));
}
export function studioOutputJS(){return `(${initStudioOutput.toString()})();`;}
