export function studioBrowserCSS(){return `
.gamma-browser { position:fixed; z-index:325; left:5vw; top:8dvh; width:90vw; height:80dvh; min-width:360px; min-height:260px; max-width:calc(100vw - 16px); max-height:calc(100dvh - 70px); display:flex; flex-direction:column; background:var(--studio-panel); color:var(--studio-ink); border:1px solid var(--studio-line); border-radius:16px; overflow:hidden; box-shadow:var(--studio-shadow); font:500 14px/1.5 Archivo,sans-serif; }.gamma-browser[hidden]{display:none}.gamma-browser.is-expanded{inset:0!important;width:100vw!important;height:100dvh!important;max-width:none;max-height:none;border-radius:0;padding-bottom:80px;box-sizing:border-box}
.gamma-browser header { display:flex; align-items:center; flex-wrap:wrap; gap:8px; padding:12px; }.gamma-browser-drag{display:flex;align-items:center;min-height:44px;padding:0 4px;color:var(--studio-muted);font-weight:750;letter-spacing:.02em;cursor:grab;user-select:none;touch-action:none}.gamma-browser-drag:active{cursor:grabbing}.gamma-browser button,.gamma-browser input { min-height:44px; box-sizing:border-box; border:1px solid var(--studio-line); border-radius:9px; background:var(--studio-panel-raised); color:var(--studio-ink); padding:8px 12px; font:500 14px Archivo,sans-serif; }.gamma-browser input{font-size:16px;min-width:80px;flex:1}.gamma-browser form{display:flex;gap:8px;flex:1;min-width:220px}.gamma-browser button{cursor:pointer}.gamma-browser button:focus-visible,.gamma-browser input:focus-visible,.gamma-browser-viewport:focus-visible,.gamma-browser-drag:focus-visible{outline:2px solid var(--studio-blue-soft);outline-offset:-2px}
.gamma-browser-status{padding:0 16px 12px;margin:0;color:var(--studio-muted);font-size:12px}.gamma-browser-viewport{flex:1;min-height:0;overflow:auto;touch-action:pan-y;background:var(--studio-panel-raised);position:relative}.gamma-browser-viewport video{display:block;width:100%;height:auto;object-fit:contain;object-position:top;user-select:none;touch-action:none}.gamma-browser-viewport iframe{border:0;width:100%;height:100%;background:var(--studio-ink)}.gamma-browser footer{display:flex;gap:8px;padding:12px}.gamma-browser footer input{min-width:0}.gamma-browser footer a{color:var(--studio-ink);padding:12px;white-space:nowrap}
.gamma-browser-resize{position:absolute;right:0;bottom:0;z-index:2;width:28px;height:28px;cursor:nwse-resize;touch-action:none}.gamma-browser-resize::after{content:'';position:absolute;right:8px;bottom:8px;width:9px;height:9px;border-right:2px solid var(--studio-blue-soft);border-bottom:2px solid var(--studio-blue-soft)}.gamma-browser.is-expanded .gamma-browser-drag,.gamma-browser.is-expanded .gamma-browser-resize{display:none}
@media(max-width:900px){.gamma-browser{inset:16px 16px 160px;width:auto;height:auto;min-width:0;min-height:240px;max-width:none;max-height:none}.gamma-browser header form{order:2;flex-basis:100%;min-width:0}.gamma-browser header{gap:8px}.gamma-browser footer{flex-wrap:wrap}.gamma-browser footer input{flex:1 0 100%}.gamma-browser footer a{padding:8px}.gamma-browser-drag{order:-1;flex:1}.gamma-browser-resize{display:none}}
.studio-content-slide{display:flex;flex-direction:column;gap:24px;min-width:0}.studio-content-slide h2{color:var(--gamma-text)}.studio-content-kicker{color:var(--gamma-primary)!important;font:500 14px Archivo,sans-serif}.studio-site-address{font-family:Azeret Mono,monospace;overflow-wrap:anywhere}.studio-slide-media{width:100%;max-height:52dvh;object-fit:contain}.studio-youtube-media{display:block;width:100%;aspect-ratio:16/9;max-height:52dvh;border:0;background:#05070a}.studio-youtube-unavailable{display:grid;min-height:220px;place-items:center;padding:24px;border:1px solid var(--studio-line);color:var(--gamma-muted);text-align:center}.studio-slide-actions{display:flex;flex-wrap:wrap;gap:10px}.studio-slide-actions button,.studio-slide-actions a{display:inline-flex;align-items:center;justify-content:center;min-height:44px;font:500 16px Archivo,sans-serif;padding:12px 24px;color:var(--gamma-bg);background:var(--gamma-primary);border:0;border-radius:9px;text-decoration:none}
@media print{.gamma-browser{display:none!important}}
`;}
function initStudioBrowser(){
 if(new URLSearchParams(location.search).has('gamma-clean')||new URLSearchParams(location.search).has('gamma-export'))return;
 document.querySelectorAll('video.studio-slide-media,audio.studio-slide-media').forEach(media=>{media.controls=false;const scope=media.closest('.studio-content-slide');scope.querySelectorAll('[data-media]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.media==='play'){if(media.paused)media.play().catch(()=>{});else media.pause();}else if(b.dataset.media==='back')media.currentTime=Math.max(0,media.currentTime-10);else{media.dataset.userMuted=String(media.dataset.userMuted!=='true');media.muted=!!window.__gammaBroadcastActive||media.dataset.userMuted==='true';b.setAttribute('aria-pressed',media.dataset.userMuted);b.textContent=media.dataset.userMuted==='true'?'Enable media audio':'Mute media audio';}}));media.addEventListener('play',()=>scope.querySelector('[data-media=play]').textContent='Pause media');media.addEventListener('pause',()=>scope.querySelector('[data-media=play]').textContent='Play media');});
 const box=document.createElement('section');box.className='gamma-browser';box.hidden=true;box.setAttribute('aria-label','Demo browser');box.innerHTML='<header><span class="gamma-browser-drag" data-testid="studio-browser-drag" tabindex="0" role="button" aria-label="Move browser window" title="Drag to move · double-click to reset">Browser</span><button data-web="back" aria-label="Previous page">←</button><button data-web="forward" aria-label="Next page">→</button><button data-web="reload" aria-label="Reload">↻</button><form><input type="url" aria-label="Site address" placeholder="https://github.com/…" required><button>Open</button></form><button data-web="zoom" aria-pressed="false">Zoom 100 %</button><button data-web="audio" aria-pressed="false">Enable audio</button><button data-web="expand" aria-label="Expand browser" aria-pressed="false">Expand</button><button data-web="close" aria-label="Close browser">Close</button></header><p class="gamma-browser-status" role="status">Demo browser · isolated session</p><div class="gamma-browser-viewport" tabindex="0" aria-label="Remote page, click to interact"></div><footer><input data-web-text aria-label="Text to type in remote page" placeholder="Text to type into selected field"><button data-web="text">Type</button><button data-web="enter">Enter</button><a target="_blank" rel="noopener noreferrer">Open separately</a></footer><div class="gamma-browser-resize" data-testid="studio-browser-resize" role="presentation"></div>';document.body.append(box);
 const viewport=box.querySelector('.gamma-browser-viewport'),img=Object.assign(document.createElement('video'),{autoplay:true,playsInline:true,muted:true,hidden:true}),input=box.querySelector('input[type=url]'),status=box.querySelector('[role=status]'),link=box.querySelector('a');let commandQueue=Promise.resolve(),token,pending=false,frame,initialized=false,peer,connecting,closing,width=1920,height=1080;img.setAttribute("aria-label","Live local browser page");img.dataset.userMuted="true";
 const setURL=url=>{input.value=url;link.href=url;};const frameKey='gamma-browser-frame-v1',minimumWidth=()=>Math.min(420,Math.max(280,innerWidth-24)),minimumHeight=()=>Math.min(280,Math.max(190,innerHeight-88));
 const clampFrame=()=>{if(box.hidden||box.classList.contains('is-expanded'))return;const width=Math.max(minimumWidth(),Math.min(innerWidth-16,box.offsetWidth)),height=Math.max(minimumHeight(),Math.min(innerHeight-70,box.offsetHeight)),left=Math.max(8,Math.min(innerWidth-width-8,parseFloat(box.style.left)||innerWidth*.05)),top=Math.max(8,Math.min(innerHeight-height-8,parseFloat(box.style.top)||innerHeight*.08));Object.assign(box.style,{width:width+'px',height:height+'px',left:left+'px',top:top+'px',right:'auto',bottom:'auto'});};
 const saveFrame=()=>{if(box.hidden||box.classList.contains('is-expanded'))return;const rect=box.getBoundingClientRect();try{localStorage.setItem(frameKey,JSON.stringify({left:rect.left,top:rect.top,width:rect.width,height:rect.height}));}catch{}};
 const restoreFrame=(reset=false)=>{if(reset){try{localStorage.removeItem(frameKey);}catch{}box.removeAttribute('style');return;}try{const saved=JSON.parse(localStorage.getItem(frameKey)||'null');if(saved){Object.assign(box.style,{left:Number(saved.left)+'px',top:Number(saved.top)+'px',width:Number(saved.width)+'px',height:Number(saved.height)+'px',right:'auto',bottom:'auto'});clampFrame();}}catch{}};
 const setExpanded=expanded=>{if(expanded)saveFrame();box.classList.toggle('is-expanded',expanded);const control=box.querySelector('[data-web=expand]');control.setAttribute('aria-pressed',String(expanded));control.textContent=expanded?'Collapse':'Expand';if(!expanded){restoreFrame();clampFrame();}};restoreFrame();
 async function connect(){if(initialized)return;initialized=true;try{const r=await fetch('/__gamma/browser/session');if(!r.ok)throw Error();const session=await r.json();token=session.token;width=session.width;height=session.height;window.__gammaBrowserMode='local';window.dispatchEvent(new Event('gamma:studio-state'));}catch{token=null;window.__gammaBrowserMode='iframe';window.dispatchEvent(new Event('gamma:studio-state'));box.querySelector('footer').querySelectorAll('input,button').forEach(el=>el.hidden=true);box.querySelectorAll('[data-web=back],[data-web=forward],[data-web=reload],[data-web=audio]').forEach(el=>el.disabled=true);status.textContent='Embedded mode: some sites reject iframes. Serve this deck with --browser for the isolated browser.';}}
 async function stream(){
  if(connecting)return connecting;if(!token||peer&&!['closed','failed'].includes(peer.connectionState))return;
  connecting=(async()=>{status.textContent='Connecting video and audio…';const pc=peer=new RTCPeerConnection({iceServers:[]}),remote=new MediaStream();pc.addTransceiver('video',{direction:'recvonly'});pc.addTransceiver('audio',{direction:'recvonly'});
   pc.ontrack=e=>{remote.addTrack(e.track);img.srcObject=remote;img.hidden=false;if(!img.isConnected)viewport.append(img);img.play().catch(()=>{status.textContent='Click Enable audio to start playback.';});window.__gammaBrowserStream=remote;window.dispatchEvent(new Event('gamma:browser-stream'));};
   pc.onconnectionstatechange=()=>{if(pc.connectionState==='connected'){window.__gammaBrowserStream=remote;window.dispatchEvent(new Event('gamma:browser-stream'));}if(pc.connectionState==='failed'||pc.connectionState==='disconnected'){status.textContent='Stream interrupted. Close and reopen the browser to reconnect.';window.__gammaBrowserStream=null;window.dispatchEvent(new Event('gamma:browser-stream'));}};
   await pc.setLocalDescription(await pc.createOffer());if(pc.iceGatheringState!=='complete')await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Video connection timed out')),10000);pc.addEventListener('icegatheringstatechange',()=>{if(pc.iceGatheringState==='complete'){clearTimeout(timer);resolve();}});});
   const r=await fetch('/__gamma/browser/stream',{method:'POST',headers:{'Content-Type':'application/json','X-Gamma-Token':token},body:JSON.stringify(pc.localDescription)}),result=await r.json();if(!r.ok)throw Error(result.error);await pc.setRemoteDescription(result.description);status.textContent='Live video · '+result.captureWidth+' × '+result.captureHeight+' · '+(result.audio?'audio available':'source has no audio track');
  })().catch(e=>{peer?.close();peer=null;status.textContent='Video unavailable: '+e.message;throw e;}).finally(()=>connecting=null);return connecting;
 }
 async function close(){box.hidden=true;peer?.close();peer=null;img.srcObject?.getTracks().forEach(t=>t.stop());img.srcObject=null;window.__gammaBrowserStream=null;window.dispatchEvent(new Event('gamma:browser-stream'));if(token){closing=(async()=>{await connecting?.catch(()=>{});await commandQueue;await fetch('/__gamma/browser/close',{method:'POST',headers:{'Content-Type':'application/json','X-Gamma-Token':token},body:'{}'}).catch(()=>{});})().finally(()=>closing=null);await closing;}document.querySelector('.gamma-orbit-hub')?.focus();}
 function command(action,data={}){const task=commandQueue.then(()=>execute(action,data));commandQueue=task.catch(()=>{});return task;}
 async function execute(action,data={}){pending=true;status.textContent='Loading…';try{const r=await fetch('/__gamma/browser',{method:'POST',headers:{'Content-Type':'application/json','X-Gamma-Token':token},body:JSON.stringify({action,...data})}),result=await r.json();if(!r.ok)throw Error(result.error);setURL(result.url);status.textContent=(result.title||result.url)+' · isolated local browser';return true;}catch(e){status.textContent=e.message;return false;}finally{pending=false;}}
 async function navigate(url){let parsed;try{parsed=new URL(url);if(!['https:','http:'].includes(parsed.protocol))throw Error();}catch{status.textContent='Enter a valid HTTP or HTTPS address.';return;}setURL(parsed.href);await connect();if(token){try{await stream();await command('navigate',{url:parsed.href});}catch{}}else{if(!frame){frame=document.createElement('iframe');frame.title='Embedded site';frame.referrerPolicy='no-referrer';frame.setAttribute('sandbox','allow-scripts allow-forms allow-same-origin allow-popups');viewport.append(frame);}frame.src=parsed.href;}}
 document.querySelectorAll('[data-studio-browser-url]').forEach(b=>b.addEventListener('click',()=>window.dispatchEvent(new CustomEvent('gamma:browser-open',{detail:{url:b.dataset.studioBrowserUrl}}))));
 Reveal.on('slidechanged',()=>document.querySelectorAll('video.studio-slide-media,audio.studio-slide-media').forEach(m=>{if(!m.closest('section.present'))m.pause();}));
 window.addEventListener('gamma:browser-open',async e=>{await closing;box.hidden=false;clampFrame();await connect();if(token){try{await stream();}catch{return;}}if(box.hidden)return;if(e.detail?.url)await navigate(e.detail.url);input.focus();});
 box.querySelector('form').addEventListener('submit',e=>{e.preventDefault();navigate(input.value);});
 box.addEventListener('click',async e=>{const action=e.target.closest('[data-web]')?.dataset.web;if(!action)return;if(action==='close'){close();}else if(action==='zoom'){const zoom=img.style.width===width+'px';img.style.width=zoom?'100%':width+'px';e.target.textContent=zoom?'Zoom 100 %':'Fit';e.target.setAttribute('aria-pressed',String(!zoom));}else if(action==='audio'){img.dataset.userMuted=String(img.dataset.userMuted!=='true');const userMuted=img.dataset.userMuted==='true';img.muted=userMuted||!!(window.__gammaBroadcastActive&&window.__gammaOutputFlags?.browser);e.target.textContent=userMuted?'Enable audio':'Mute audio';e.target.setAttribute('aria-pressed',String(!userMuted));img.play().catch(()=>{});window.dispatchEvent(new Event('gamma:browser-stream'));}else if(action==='expand'){setExpanded(!box.classList.contains('is-expanded'));}else if(action==='text'){const field=box.querySelector('[data-web-text]');if(await command('text',{text:field.value}))field.value='';}else if(action==='enter')command('key',{key:'Enter'});else command(action);});
 const drag=box.querySelector('[data-testid=studio-browser-drag]'),resize=box.querySelector('[data-testid=studio-browser-resize]');drag.addEventListener('dblclick',()=>restoreFrame(true));drag.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();restoreFrame(true);}});drag.addEventListener('pointerdown',event=>{if(event.button!==0||box.classList.contains('is-expanded'))return;event.preventDefault();const rect=box.getBoundingClientRect(),offsetX=event.clientX-rect.left,offsetY=event.clientY-rect.top;drag.setPointerCapture(event.pointerId);const move=pointer=>{box.style.left=Math.max(8,Math.min(innerWidth-box.offsetWidth-8,pointer.clientX-offsetX))+'px';box.style.top=Math.max(8,Math.min(innerHeight-box.offsetHeight-8,pointer.clientY-offsetY))+'px';box.style.right='auto';box.style.bottom='auto';};const end=pointer=>{drag.releasePointerCapture(pointer.pointerId);drag.removeEventListener('pointermove',move);drag.removeEventListener('pointerup',end);drag.removeEventListener('pointercancel',end);saveFrame();};drag.addEventListener('pointermove',move);drag.addEventListener('pointerup',end);drag.addEventListener('pointercancel',end);});resize.addEventListener('pointerdown',event=>{if(event.button!==0||box.classList.contains('is-expanded'))return;event.preventDefault();const rect=box.getBoundingClientRect(),origin={x:event.clientX,y:event.clientY,width:rect.width,height:rect.height};resize.setPointerCapture(event.pointerId);const move=pointer=>{box.style.width=Math.max(minimumWidth(),Math.min(innerWidth-rect.left-8,origin.width+pointer.clientX-origin.x))+'px';box.style.height=Math.max(minimumHeight(),Math.min(innerHeight-rect.top-8,origin.height+pointer.clientY-origin.y))+'px';};const end=pointer=>{resize.releasePointerCapture(pointer.pointerId);resize.removeEventListener('pointermove',move);resize.removeEventListener('pointerup',end);resize.removeEventListener('pointercancel',end);saveFrame();};resize.addEventListener('pointermove',move);resize.addEventListener('pointerup',end);resize.addEventListener('pointercancel',end);});window.addEventListener('resize',()=>{clampFrame();saveFrame();});
 let touchY=null,touchX=null,touchMoved=false;img.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch')return;touchY=e.clientY;touchX=e.clientX;touchMoved=false;});img.addEventListener('pointermove',e=>{if(e.pointerType!=='touch'||touchY===null||!token)return;const delta=touchY-e.clientY,dx=touchX-e.clientX;if(Math.abs(dx)>12&&img.clientWidth>viewport.clientWidth){viewport.scrollLeft+=dx;touchX=e.clientX;touchMoved=true;}if(Math.abs(delta)>12){touchMoved=true;touchY=e.clientY;command('wheel',{y:delta*height/Math.max(200,img.clientHeight)});}});img.addEventListener('pointerup',()=>touchY=null);img.addEventListener('pointercancel',()=>touchY=null);
 img.addEventListener('click',e=>{if(touchMoved){touchMoved=false;return;}const r=img.getBoundingClientRect(),scale=r.width/width;command('click',{x:(e.clientX-r.left)/scale,y:(e.clientY-r.top)/scale});viewport.focus();});
 viewport.addEventListener('wheel',e=>{if(!token)return;e.preventDefault();command('wheel',{y:e.deltaY});},{passive:false});
 viewport.addEventListener('keydown',e=>{if(!token||e.ctrlKey||e.metaKey||e.altKey)return;e.preventDefault();if(e.key.length===1)command('text',{text:e.key});else command('key',{key:e.key});});
 box.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Escape'){close();}});
}
export function studioBrowserJS(){return `(${initStudioBrowser.toString()})();`;}
