import test from 'node:test';import assert from 'node:assert/strict';import {loadDeck}from'../src/loader/index.js';import{renderExplainer}from'../src/engine/components/explainer.js';
import {renderMechanism} from '../src/engine/components/mechanism.js';
test('LLM mechanism specs are bounded and cannot inject markup through labels or values',()=>{const slide={layout:'visual',title:'<script>x</script>',visual:{alt:'Mechanism',mechanism:{type:'allocation',status:'Research',steps:[{label:'<img onerror=x>',value:'70 %'},{label:'B',value:'30 %'}]}}};assert.equal(loadDeck(JSON.stringify({slides:[slide]})).slides.length,1);const html=renderMechanism(slide);assert.ok(html.includes('--share:0.7'));assert.ok(!html.includes('<script>')&&!html.includes('<'+'img '));const invalid=structuredClone(slide);invalid.visual.mechanism.steps=Array(5).fill({label:'Too many'});assert.throws(()=>loadDeck(JSON.stringify({slides:[invalid]})),/Invalid deck/);});
test('negative comparison endpoints leave enough room for their full value label',async()=>{const d3=await import('d3');const {buildGPUScene}=await import('../src/engine/components/d3-webgpu-runtime.js');const model={type:'bar',options:{video_readable:true,format_y:'percent'},labels:['Loss','Gain'],series:[{name:'Return',values:[-21.6,12]}]};for(const width of[300,1136]){const s=buildGPUScene(model,width,360,d3),label=s.texts.find(t=>t.value.includes('21.6')&&t.anchor==='end');assert.ok(label);assert.ok(label.x-label.value.length*label.size*.6>=0,JSON.stringify(label));}});
const scene={layout:'visual',title:'Comprendre',visual:{alt:'Un mécanisme',story:{type:'recovery',labels:['100','50','100']}}};
test('declarative educational visuals load without an external image; existing images remain valid',()=>{assert.equal(loadDeck(JSON.stringify({slides:[scene]})).slides[0].visual.story.type,'recovery');assert.equal(loadDeck(JSON.stringify({slides:[{layout:'visual',visual:{src:'https://example.com/image.png',alt:'Image'}}]})).slides.length,1);assert.throws(()=>loadDeck(JSON.stringify({slides:[{...scene,visual:{alt:'Missing both'}}]})),/Invalid deck/);assert.throws(()=>loadDeck(JSON.stringify({slides:[{...scene,visual:{...scene.visual,story:{type:'script',labels:['x']}}}]})),/Invalid deck/);});
test('visual labels, title and accessibility text cannot inject markup',()=>{const html=renderExplainer({...scene,title:'<script>evil()</script>',visual:{...scene.visual,alt:'" onload="evil()',story:{type:'recovery',labels:['<image onload="evil()">','50','100']}}});assert.ok(!html.includes('<script>'));assert.ok(!html.includes('<image '));assert.ok(html.includes('&lt;script&gt;'));assert.ok(html.includes('&quot; onload=&quot;'));});
test('loss and recovery is a V, with a smaller base for the recovery percentage',()=>{const html=renderExplainer(scene);assert.match(html,/M150 100 L480 310 L810 100/);assert.ok(html.includes('−50 %')&&html.includes('+100 %'));});

test('the focused doughnut value is a slice; an absent focus remains the total',async()=>{const {buildEChartsConfig}=await import('../src/engine/components/chart-builder.js');const {getTheme}=await import('../src/themes/index.js');const chart={type:'doughnut',data:{labels:['DELL','Rest'],datasets:[{values:[66.87,33.13]}]},options:{format_y:'percent',center_index:0,center_label:'DELL'}};const config=buildEChartsConfig(chart,getTheme('signal-room'));assert.match(config.title.text,/66\.87/);assert.deepEqual(config.series[0].data.map(d=>d.value),[66.87,33.13]);delete chart.options.center_index;assert.match(buildEChartsConfig(chart,getTheme('signal-room')).title.text,/100/);});
test('video grouped bars fit their category and never acquire negative height',async()=>{const d3=await import('d3');const {buildGPUScene}=await import('../src/engine/components/d3-webgpu-runtime.js');const model={type:'bar',options:{video_readable:true},labels:['Base','21 sessions','63 sessions'],series:[{name:'Annual gain',values:[44.9,33.4,36.3]},{name:'Worst loss',values:[18.7,15.2,15.2]}]};for(const [width,height]of[[1136,432],[342,360],[300,200]]){const scene=buildGPUScene(model,width,height,d3);assert.ok(scene.marks.every(m=>Number.isFinite(m.h)&&m.h>0));for(let i=0;i<2;i++){const previousBottom=Math.max(...scene.marks.filter(m=>m.key===i).map(m=>m.y+m.h));const label=scene.texts.find(t=>t.value===model.labels[i+1]);assert.ok(previousBottom<label.y-label.size/2,JSON.stringify({width,height,previousBottom,label}));}}});

test('a trailing stop preserves discrete decisions without interpolation',async()=>{
 const {buildEChartsConfig}=await import('../src/engine/components/chart-builder.js');
 const {getTheme}=await import('../src/themes/index.js');
 const chart={type:'line',data:{labels:['Entry','Activate','Peak','Pullback'],datasets:[{label:'Price',values:[100,114,122,119]},{label:'Stop',values:[90,108,116,116],step:'end'}]},options:{smooth:false,y_min:80,y_max:130}};
 const config=buildEChartsConfig(chart,getTheme('signal-room'));
 assert.equal(config.series[0].smooth,false);assert.equal(config.series[1].smooth,false);assert.equal(config.series[1].step,'end');assert.deepEqual(config.series[1].data,[90,108,116,116]);
});
test('enlarged workflow labels remain inside their node without changing the ordinary diagram',async()=>{
 const {frameDiagramSVG}=await import('../src/engine/components/archify-framing.js');
 const svg='<svg viewBox="0 0 600 400"><g data-node-id="a"><rect x="40" y="80" width="520" height="220"/><text data-node-label="" x="300" y="107" font-size="11">Protect</text></g></svg>';
 const normal=frameDiagramSVG(svg,'workflow');assert.match(normal,/y="107" font-size="11"/);
 const enlarged=frameDiagramSVG(svg,'workflow',{node:40,edge:24,context:24});assert.match(enlarged,/x="300" y="203.2" font-size="40"/);
});
