import test from'node:test';import assert from'node:assert/strict';import{mkdtempSync,writeFileSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import{serveRepositoryPresentation}from'../src/repository/server.js';
async function fixture(fn){const dir=mkdtempSync(join(tmpdir(),'gamma-pty-test-'));writeFileSync(join(dir,'index.html'),'unchanged');const live=await serveRepositoryPresentation(dir,{port:0,terminal:true,cwd:dir});const session=await(await fetch(live.url+'__gamma/terminal/session')).json();const post=(path,body,token=session.token)=>fetch(live.url+'__gamma/terminal'+path,{method:'POST',headers:{'Content-Type':'application/json','X-Gamma-Token':token},body:JSON.stringify(body)});try{await fn({dir,live,post});}finally{await new Promise(r=>live.server.close(r));rmSync(dir,{recursive:true,force:true});}}
function events(response){const reader=response.body.getReader(),decoder=new TextDecoder();let pending='';return {cancel:()=>reader.cancel(),async next(){while(!pending.includes('\n')){const c=await reader.read();if(c.done)return null;pending+=decoder.decode(c.value,{stream:true});}const n=pending.indexOf('\n'),e=JSON.parse(pending.slice(0,n));pending=pending.slice(n+1);return e;}};}
async function until(stream,predicate){for(let i=0;i<1000;i++){const e=await stream.next();if(!e)throw Error('Stream ended before expected event');if(predicate(e))return e;}throw Error('Too many events');}
test('PTY supplies a real terminal, accepts input and retains cwd after exit',{timeout:10000},async()=>fixture(async({dir,post})=>{const r=await post('/pty',{command:'test -t 0 && printf TTY_READY; read value; printf "ANSWER:%s" "$value"; cd /tmp',cols:80,rows:24});assert.equal(r.status,200);const s=events(r),ready=await s.next();assert.equal(ready.type,'ready');await until(s,e=>e.data?.includes('TTY_READY'));assert.equal((await post('/pty/'+ready.id+'/input',{data:'bonjour\r'})).status,200);let text='';const exit=await until(s,e=>{text+=e.data||'';return e.type==='exit';});assert.match(text,/ANSWER:bonjour/);assert.equal(exit.exitCode,0);assert.equal(exit.cwd,'/tmp');}));
test('session controls enforce origin/token/id and validate payloads',{timeout:10000},async()=>fixture(async({post,live})=>{assert.equal((await post('/pty',{command:'echo nope',cols:80,rows:24},'wrong')).status,403);assert.equal((await post('/pty',null)).status,400);assert.equal((await post('/pty',{command:'echo nope',cols:0,rows:24})).status,400);const r=await post('/pty',{command:'sleep 60',cols:80,rows:24}),s=events(r),ready=await s.next();assert.equal((await post('/pty',{command:'echo concurrent',cols:80,rows:24})).status,409);assert.equal((await post('/pty/'+ready.id+'/input',{data:'x'},'wrong')).status,403);assert.equal((await post('/pty/'+'0'.repeat(48)+'/stop',{})).status,404);assert.equal((await post('/pty/'+ready.id+'/resize',{cols:100,rows:30})).status,200);assert.equal((await post('/pty/'+ready.id+'/resize',{cols:1000,rows:30})).status,400);await post('/pty/'+ready.id+'/stop',{});const exit=await until(s,e=>e.type==='exit');assert.ok(exit.signal||exit.exitCode);assert.equal(await(await fetch(live.url)).text(),'unchanged');}));
test('disconnect kills the owned process and releases the command slot',{timeout:10000},async()=>fixture(async({post})=>{const r=await post('/pty',{command:'printf "PID:%s\\n" "$$"; sleep 60',cols:80,rows:24}),s=events(r);await s.next();const message=await until(s,e=>e.data?.includes('PID:')),pid=Number(message.data.match(/PID:(\d+)/)[1]);await s.cancel();for(let i=0;i<50;i++){try{process.kill(pid,0);}catch{return;}await new Promise(r=>setTimeout(r,50));}assert.fail('Abandoned PTY process still alive');}));
test('server shutdown stops a running PTY instead of waiting forever',{timeout:10000},async()=>fixture(async({post,live})=>{const s=events(await post('/pty',{command:'sleep 60',cols:80,rows:24}));await s.next();const closed=new Promise(r=>live.server.close(r));await until(s,e=>e.type==='exit');await closed;}));
test('noisy output and lost heartbeats terminate their owned process',{timeout:10000},async()=>{
 const {createPTYSession}=await import('../src/repository/terminal-pty.js');const{Writable}=await import('node:stream');
 for(const [command,options,reason]of[['yes data',{maxOutput:128},'Output too large'],['sleep 60',{idleMs:30},'Terminal connection lost']]){
 const messages=[];const response=new Writable({write(chunk,encoding,next){messages.push(JSON.parse(chunk));next();}});response.writeHead=()=>{};
 const done=new Promise(r=>response.once('finish',r));const session=createPTYSession({getDirectory:()=>tmpdir(),setDirectory:()=>{},...options});session.start(response,{command,cols:80,rows:24});await done;assert.match(messages.at(-1).error,new RegExp(reason));assert.equal(session.busy,false);
 }
});
