export const analystProof = {
  id: 'analyst-proof',
  label: 'Analyst Proof',
  description: 'A marked-up research proof for reviewing numbers, assumptions, and decisions',
  purpose: 'Review the evidence',
  aesthetic: 'editorial',
  presentationTheme: 'analyst-proof',
  themeFamily: 'boardroom',
  mode: 'light',
  primary: '#1748D5',
  secondary: '#5E46A8',
  accent: '#A05A14',
  positive: '#087D67',
  negative: '#B7352D',
  warning: '#A05A14',
  forecast: '#5E46A8',
  background: '#F3F0E8',
  surface: '#FBF9F3',
  surfaceLight: '#E8E4DA',
  text: '#111318',
  textMuted: '#62646B',
  hairline: '#CFC9BD',
  ink: '#111318',
  paper: '#F3F0E8',
  gradient: '#1748D5',
  gradientAlt: '#5E46A8',
  fontHeading: 'Source Serif 4',
  fontBody: 'Archivo',
  fontDisplay: 'Source Serif 4',
  fontMono: 'Azeret Mono',
  cardBg: 'transparent',
  cardBorder: '#CFC9BD',
  chartBg: 'transparent',
  footerBg: 'rgba(243, 240, 232, 0.96)',
  tableBorder: '#CFC9BD',
  tableHeaderBg: 'transparent',
  tableText: '#111318',
  tableHover: 'rgba(23, 72, 213, 0.05)',
  highlightBg: 'rgba(23, 72, 213, 0.05)',
  badgeBg: 'transparent',
  badgeBorder: 'transparent',
};
