export const cuttingRoom = {
  id: 'cutting-room',
  label: 'Cutting Room',
  description: 'A cinematic work print that turns the deck into a paced financial narrative',
  purpose: 'Tell the story',
  aesthetic: 'editorial',
  presentationTheme: 'cutting-room',
  themeFamily: 'boardroom',
  mode: 'dark',
  primary: '#FF5A1F',
  secondary: '#FFD166',
  accent: '#7CC7FF',
  positive: '#67D5A5',
  negative: '#FF7D72',
  warning: '#FFD166',
  forecast: '#7CC7FF',
  background: '#080808',
  surface: '#111111',
  surfaceLight: '#1D1D1D',
  text: '#F4F0E7',
  textMuted: '#B5ADA0',
  hairline: '#3A3732',
  ink: '#080808',
  paper: '#F4F0E7',
  gradient: '#FF5A1F',
  gradientAlt: '#FFD166',
  fontHeading: 'Archivo',
  fontBody: 'Archivo',
  fontDisplay: 'Source Serif 4',
  fontMono: 'Azeret Mono',
  cardBg: 'transparent',
  cardBorder: '#3A3732',
  chartBg: 'transparent',
  footerBg: 'rgba(8, 8, 8, 0.96)',
  tableBorder: '#3A3732',
  tableHeaderBg: 'transparent',
  tableText: '#F4F0E7',
  tableHover: 'rgba(255, 90, 31, 0.08)',
  highlightBg: 'rgba(255, 90, 31, 0.08)',
  badgeBg: 'transparent',
  badgeBorder: 'transparent',
};
