export const signalRoom = {
  id: 'signal-room',
  label: 'Signal Room',
  description: 'An emissive decision field where hierarchy comes from depth, not containers',
  purpose: 'Decide from the signal',
  aesthetic: 'editorial',
  presentationTheme: 'signal-room',
  themeFamily: 'boardroom',
  mode: 'dark',
  primary: '#FFB000',
  secondary: '#8BA8FF',
  accent: '#C7B8FF',
  positive: '#3FD49A',
  negative: '#FF6F66',
  warning: '#FFB000',
  forecast: '#8BA8FF',
  background: '#05070A',
  surface: '#0A0E13',
  surfaceLight: '#141B24',
  text: '#F3F6F2',
  textMuted: '#A3ADB8',
  hairline: '#26313D',
  ink: '#05070A',
  paper: '#F3F6F2',
  gradient: '#FFB000',
  gradientAlt: '#8BA8FF',
  fontHeading: 'Azeret Mono',
  fontBody: 'Archivo',
  fontDisplay: 'Source Serif 4',
  fontMono: 'Azeret Mono',
  cardBg: 'transparent',
  cardBorder: '#26313D',
  chartBg: 'transparent',
  footerBg: 'rgba(5, 7, 10, 0.96)',
  tableBorder: '#26313D',
  tableHeaderBg: 'transparent',
  tableText: '#F3F6F2',
  tableHover: 'rgba(255, 176, 0, 0.07)',
  highlightBg: 'rgba(255, 176, 0, 0.07)',
  badgeBg: 'transparent',
  badgeBorder: 'transparent',
};
