const source = document.querySelector('#source');
const slideList = document.querySelector('#thumbnail-list');
const feedback = document.querySelector('#feedback');
const preview = document.querySelector('#renderer-preview');
const rendererStatus = document.querySelector('#renderer-status');
const templateDialog = document.querySelector('#template-dialog');
const templateList = document.querySelector('#template-list');
const richInspector = document.querySelector('#rich-inspector');
const rich = Object.fromEntries(['title', 'subtitle', 'layout', 'media-kind', 'media-src', 'notes', 'configuration'].map(name => [name, document.querySelector(`#rich-${name}`)]));
const markdownInspector = document.querySelector('#markdown-inspector');
const markdown = Object.fromEntries(['title', 'subtitle', 'notes'].map(name => [name, document.querySelector(`#markdown-${name}`)]));
const control = { presentation: document.querySelector('#presentation-elapsed'), slide: document.querySelector('#slide-elapsed'), minutes: document.querySelector('#countdown-minutes'), toggle: document.querySelector('#toggle-countdown'), status: document.querySelector('#countdown-status'), cue: document.querySelector('#copilot-cue'), cli: document.querySelector('#copilot-cli'), copilotStatus: document.querySelector('#copilot-status'), output: document.querySelector('#copilot-output'), endpoint: document.querySelector('#mcp-endpoint'), token: document.querySelector('#mcp-token'), scope: document.querySelector('#mcp-scope'), approvalStatus: document.querySelector('#approval-status'), operatorRequests: document.querySelector('#operator-requests') };
let pendingUpdate; let selectedSlide = 0; let currentState = {}; let previewRevision = -1; let thumbnailTimer; let draggingSlide = null;
const escapeHtml = value => String(value || '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[char]);
const formatTime = milliseconds => { const seconds = Math.max(0, Math.ceil((milliseconds || 0) / 1000)); return `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`; };

function markdownSlides(value) { return value.split(/\n\s*(?:---|\n\s*\n)\s*\n/g).filter(Boolean).map((text, index) => ({ start: value.indexOf(text), title: text.match(/^#\s+(.+)$/m)?.[1]?.trim() || `Slide ${index + 1}`, subtitle: text.match(/^##\s+(.+)$/m)?.[1]?.trim() || '', image: text.match(/^!\[[^\]]*\]\(([^\s)]+)\)$/m)?.[1] || '', hasMedia: /^@\[(?:video|audio)(?::[^\]]*)?\]\([^\s)]+\)$/mi.test(text) })); }
const slides = () => currentState.sourceKind && currentState.sourceKind !== 'markdown' ? (currentState.slides || []) : markdownSlides(source.value);
function renderThumbnails() {
  const all = slides(); selectedSlide = Math.min(selectedSlide, Math.max(0, all.length - 1)); const virtual = all.length > 80, row = 120, visible = virtual ? 70 : all.length; const start = virtual ? Math.max(0, Math.min(all.length - visible, Math.floor(slideList.scrollTop / row) - 12)) : 0, end = Math.min(all.length, start + visible);
  slideList.innerHTML = `${virtual ? `<div aria-hidden="true" style="height:${start * row}px"></div>` : ''}${all.slice(start, end).map((slide, local) => { const index = start + local, kind = slide.hasChart ? 'Chart' : slide.hasDiagram ? 'Diagram' : slide.hasMedia ? 'Media' : slide.layout && slide.layout !== 'bullets' ? slide.layout : ''; return `<button class="thumbnail${index === selectedSlide ? ' selected' : ''}" data-index="${index}" draggable="true" aria-current="${index === selectedSlide ? 'true' : 'false'}"><span class="thumbnail-number">${String(index + 1).padStart(2, '0')}</span><span class="thumbnail-canvas">${slide.image ? `<img src="${escapeHtml(slide.image)}" alt="">` : ''}${kind ? `<em>${escapeHtml(kind)}</em>` : ''}<strong>${escapeHtml(slide.title)}</strong>${slide.subtitle ? `<small>${escapeHtml(slide.subtitle)}</small>` : ''}</span><span class="thumbnail-title">${escapeHtml(slide.title)}</span></button>`; }).join('')}${virtual ? `<div aria-hidden="true" style="height:${Math.max(0, all.length - end) * row}px"></div>` : ''}`;
  document.querySelector('#document-meta').textContent = `${all.length} slides`; document.querySelector('#deck-duration').textContent = virtual ? `${all.length} slides · optimized rail` : `Estimated duration: ${Math.max(1, Math.round(source.value.trim().split(/\s+/).filter(Boolean).length / 130))} min`; document.querySelector('#current-slide-label').textContent = `Slide ${selectedSlide + 1} of ${all.length}`;
  document.querySelector('#move-slide-up').disabled = selectedSlide === 0 || currentState.renderState === 'rendering'; document.querySelector('#move-slide-down').disabled = selectedSlide >= all.length - 1 || currentState.renderState === 'rendering'; document.querySelector('#duplicate-slide').disabled = currentState.renderState === 'rendering'; document.querySelector('#delete-slide').disabled = currentState.renderState === 'rendering';
}
const setFeedback = message => { feedback.textContent = message; };
function selectSlide(index, focus = false) { selectedSlide = index; const range = currentState.sourceKind !== 'markdown' ? currentState.sourceRanges?.[index] : markdownSlides(source.value)[index]; if (range) { source.setSelectionRange(range.start, range.start); source.scrollTop = Math.max(0, source.value.slice(0, range.start).split('\n').length * 20 - source.clientHeight / 3); if (focus) source.focus(); } renderThumbnails(); window.gammaDesktop.navigate(index); }
function updateSource() { clearTimeout(pendingUpdate); renderThumbnails(); setFeedback('Local change · render pending…'); pendingUpdate = setTimeout(() => window.gammaDesktop.updateSource(source.value), 300); }
function insertAtCursor(value) { source.setRangeText(value, source.selectionStart, source.selectionEnd, 'end'); source.dispatchEvent(new Event('input', { bubbles: true })); source.focus(); }
async function run(message, action) { setFeedback(message); try { const result = await action(); if (result) applyState(result, true); setFeedback(result?.dirty ? 'Local changes' : 'Saved locally'); } catch (error) { setFeedback(`Error: ${error instanceof Error ? error.message : 'action unavailable'}`); } }
function renderTemplates(templates = currentState.templates || []) {
  templateList.replaceChildren(...templates.map(template => {
    const option = document.createElement('button'); option.type = 'button'; option.className = 'template-option'; option.dataset.templateId = template.id;
    const copy = document.createElement('div'); const title = document.createElement('strong'); const description = document.createElement('p'); const kind = document.createElement('span');
    title.textContent = template.title; description.textContent = template.description; kind.textContent = `${template.kind} · ${template.theme}`;
    copy.append(title, description); option.append(copy, kind); return option;
  }));
}
function openTemplateDialog() {
  renderTemplates();
  if (!templateDialog.open) templateDialog.showModal();
}
function syncInspectors(state) { const editor = state.currentSlide?.editor, isRich = Boolean(editor), isMarkdown = state.sourceKind === 'markdown'; richInspector.hidden = !isRich; markdownInspector.hidden = !isMarkdown; document.querySelectorAll('[data-insert]').forEach(button => { button.hidden = isRich; }); if (isMarkdown) { markdown.title.value = state.currentSlide?.title || ''; markdown.subtitle.value = state.currentSlide?.subtitle || ''; markdown.notes.value = state.currentSlide?.notes || ''; } if (!editor) return; rich.layout.innerHTML = (state.richLayouts || []).map(layout => `<option value="${escapeHtml(layout)}">${escapeHtml(layout)}</option>`).join(''); rich.title.value = editor.title; rich.subtitle.value = editor.subtitle; rich.notes.value = editor.notes; rich.layout.value = editor.layout; rich['media-kind'].value = editor.media.kind; rich['media-src'].value = editor.media.src; rich.configuration.value = editor.configuration; }
function renderOperatorRequests(requests = []) {
  const pending = requests.filter(request => request.status === 'pending' || request.status === 'running');
  control.approvalStatus.textContent = pending.length ? `${pending.length} live action${pending.length === 1 ? '' : 's'} awaiting operator approval.` : 'No pending co-pilot actions.';
  control.operatorRequests.replaceChildren(...pending.map(request => {
    const item = document.createElement('article'); item.className = `operator-request ${request.status === 'running' ? 'is-running' : ''}`;
    const heading = document.createElement('strong'); heading.textContent = request.label || request.action || 'Live action';
    const note = document.createElement('p'); note.textContent = request.note || 'No additional note.';
    const actions = document.createElement('div'); actions.className = 'compact-actions';
    const approve = document.createElement('button'); approve.type = 'button'; approve.dataset.operatorRequest = request.id; approve.dataset.operatorDecision = 'approve'; approve.textContent = request.status === 'running' ? 'Running…' : 'Approve & run'; approve.disabled = request.status === 'running';
    const reject = document.createElement('button'); reject.type = 'button'; reject.dataset.operatorRequest = request.id; reject.dataset.operatorDecision = 'reject'; reject.textContent = 'Reject'; reject.disabled = request.status === 'running';
    actions.append(approve, reject); item.append(heading, note, actions); return item;
  }));
}
function syncControlRoom(state) {
  const live = state.timing || {}, cue = state.cue, mcp = state.mcp || {}, copilot = state.copilot || {};
  control.presentation.textContent = formatTime(live.presentationElapsedMs); control.slide.textContent = formatTime(live.slideElapsedMs); control.toggle.textContent = live.countdownRunning ? 'Pause' : 'Start'; control.status.textContent = live.overdue ? 'Time is up.' : live.countdownRemainingMs ? `${live.countdownRunning ? 'Running' : 'Paused'} · ${formatTime(live.countdownRemainingMs)} remaining` : 'No countdown running.';
  control.status.classList.toggle('is-overdue', Boolean(live.overdue)); if (cue && document.activeElement !== control.cue) control.cue.value = cue.text; if (!cue && document.activeElement !== control.cue) control.cue.value = '';
  control.endpoint.value = mcp.endpoint || ''; control.token.value = mcp.token || ''; control.scope.textContent = mcp.scope || 'Local MCP unavailable.'; renderOperatorRequests(state.operatorRequests || []);
  const available = copilot.available || {}; [...control.cli.options].forEach(option => { option.disabled = !available[option.value]; }); if (control.cli.options[control.cli.selectedIndex]?.disabled) control.cli.value = available.codex ? 'codex' : 'claude'; control.copilotStatus.textContent = copilot.status || 'Choose a local CLI to draft a private co-pilot response.'; control.output.hidden = !copilot.output; control.output.textContent = copilot.output || ''; document.querySelector('#run-copilot').disabled = Boolean(copilot.running || (!available.codex && !available.claude)); document.querySelector('#run-copilot').textContent = copilot.running ? 'Local co-pilot is working…' : 'Ask local co-pilot';
}
function applyState(state = {}, forceSource = false) {
  currentState = { ...currentState, ...state }; if (typeof state.source === 'string' && (forceSource || document.activeElement !== source)) source.value = state.source; if (state.title) document.querySelector('#document-name').textContent = state.title; if (Number.isFinite(state.currentIndex)) selectedSlide = state.currentIndex;
  const theme = document.querySelector('#theme'), display = document.querySelector('#display'); if (Array.isArray(state.themes) && !theme.options.length) theme.innerHTML = state.themes.map(item => `<option value="${escapeHtml(item.name)}">${escapeHtml(item.label || item.name)}</option>`).join(''); if (Array.isArray(state.displays) && !display.options.length) display.innerHTML = state.displays.map(item => `<option value="${item.id}">${escapeHtml(item.label)}</option>`).join(''); if (state.theme) theme.value = state.theme; if (state.stageDisplayId) display.value = state.stageDisplayId;
  const isRich = state.sourceKind && state.sourceKind !== 'markdown'; source.classList.toggle('deck-source', isRich); source.spellcheck = !isRich; document.querySelector('#source-language').textContent = state.sourceLanguage || 'Markdown'; document.querySelector('#source-help').textContent = isRich ? `${state.sourceLanguage} is the source of truth. The inspector edits the selected slide, while full configuration covers charts, diagrams, media and animations.` : 'This text supports you and is not projected.'; syncInspectors(state);
  if (previewRevision !== state.rendererRevision) { previewRevision = state.rendererRevision; preview.src = `${state.rendererUrl}#/${state.currentIndex || 0}`; } else preview.contentWindow?.postMessage({ type: 'gamma-presenter-navigate', index: state.currentIndex || 0 }, '*'); preview.setAttribute('aria-busy', String(state.renderState === 'rendering'));
  rendererStatus.textContent = state.renderState === 'rendering' ? 'Gamma render in progress…' : state.renderState === 'invalid' ? 'Last valid render preserved' : isRich ? 'Rich Gamma render · source and inspector synchronized' : 'Live Gamma render'; syncControlRoom(state);
  if (templateDialog.open) renderTemplates();
  if (state.error) setFeedback(`Error${state.error.line ? ` on line ${state.error.line}${state.error.column ? `:${state.error.column}` : ''}` : ''}: ${state.error.message}`); else if (state.recoveryRestored) setFeedback('Local draft recovered · save it to keep it'); else if (state.renderState === 'ready' && state.dirty) setFeedback('Local changes · render up to date'); renderThumbnails(); document.title = `${state.title || 'Gamma Presenter'} — Gamma Presenter`;
}
source.addEventListener('input', updateSource); slideList.addEventListener('click', event => { const item = event.target.closest('[data-index]'); if (item) selectSlide(Number(item.dataset.index), true); });
slideList.addEventListener('dragstart', event => { const item = event.target.closest('[data-index]'); if (!item) return; draggingSlide = Number(item.dataset.index); event.dataTransfer.effectAllowed = 'move'; event.dataTransfer.setData('text/plain', String(draggingSlide)); item.classList.add('dragging'); });
slideList.addEventListener('dragover', event => { if (draggingSlide === null || !event.target.closest('[data-index]')) return; event.preventDefault(); event.dataTransfer.dropEffect = 'move'; });
slideList.addEventListener('drop', event => { const item = event.target.closest('[data-index]'); if (!item || draggingSlide === null) return; event.preventDefault(); const destination = Number(item.dataset.index); const origin = draggingSlide; draggingSlide = null; document.querySelectorAll('.thumbnail.dragging').forEach(node => node.classList.remove('dragging')); if (origin !== destination) mutateSlides('move', destination); });
slideList.addEventListener('dragend', () => { draggingSlide = null; document.querySelectorAll('.thumbnail.dragging').forEach(node => node.classList.remove('dragging')); });
slideList.addEventListener('scroll', () => { if (slides().length > 80) { clearTimeout(thumbnailTimer); thumbnailTimer = setTimeout(renderThumbnails, 40); } });
const mutateSlides = (action, targetIndex) => run({ add: 'Adding slide…', duplicate: 'Duplicating slide…', delete: 'Deleting slide…', move: 'Moving slide…' }[action], () => window.gammaDesktop.mutateSlides(action, selectedSlide, targetIndex));
document.querySelector('#add-slide').addEventListener('click', () => mutateSlides('add'));
document.querySelector('#duplicate-slide').addEventListener('click', () => mutateSlides('duplicate'));
document.querySelector('#delete-slide').addEventListener('click', () => mutateSlides('delete'));
document.querySelector('#move-slide-up').addEventListener('click', () => mutateSlides('move', selectedSlide - 1));
document.querySelector('#move-slide-down').addEventListener('click', () => mutateSlides('move', selectedSlide + 1));
document.querySelectorAll('[data-insert]').forEach(button => button.addEventListener('click', () => insertAtCursor(button.dataset.insert.replaceAll('\\n', '\n'))));
document.querySelector('#import-media').addEventListener('click', () => run('Choosing local media…', () => window.gammaDesktop.importMedia(selectedSlide)));
document.querySelector('#open-templates').addEventListener('click', openTemplateDialog);
document.querySelector('#close-templates').addEventListener('click', () => templateDialog.close());
templateDialog.addEventListener('click', event => { if (event.target === templateDialog) templateDialog.close(); });
templateList.addEventListener('click', event => {
  const option = event.target.closest('[data-template-id]'); if (!option) return;
  const template = (currentState.templates || []).find(item => item.id === option.dataset.templateId); if (!template) return;
  if (currentState.dirty && !window.confirm(`Start from “${template.title}”? Unsaved changes in the current presentation will be replaced.`)) return;
  templateDialog.close(); run(`Starting ${template.title}…`, () => window.gammaDesktop.applyTemplate(template.id));
});
document.addEventListener('dragover', event => { if (!event.dataTransfer?.types.includes('Files')) return; event.preventDefault(); document.body.classList.add('dragging-media'); });
document.addEventListener('dragleave', event => { if (event.relatedTarget) return; document.body.classList.remove('dragging-media'); });
document.addEventListener('drop', event => { if (!event.dataTransfer?.files?.length) return; event.preventDefault(); document.body.classList.remove('dragging-media'); run('Importing dropped media…', () => window.gammaDesktop.importDroppedMedia(event.dataTransfer.files[0], selectedSlide)); });
for (const key of ['title', 'subtitle', 'layout', 'media-kind', 'media-src', 'notes']) rich[key].addEventListener('change', () => run('Updating slide…', () => window.gammaDesktop.patchRichSlide(selectedSlide, { title: rich.title.value, subtitle: rich.subtitle.value, notes: rich.notes.value, layout: rich.layout.value, media: { kind: rich['media-kind'].value, src: rich['media-src'].value } })));
document.querySelector('#apply-markdown-slide').addEventListener('click', () => run('Updating slide…', () => window.gammaDesktop.patchMarkdownSlide(selectedSlide, { title: markdown.title.value, subtitle: markdown.subtitle.value, notes: markdown.notes.value })));
document.querySelector('#apply-rich-configuration').addEventListener('click', () => run('Validating configuration…', () => window.gammaDesktop.patchRichSlide(selectedSlide, { configuration: rich.configuration.value }))); document.querySelector('#theme').addEventListener('change', event => run('Applying theme…', () => window.gammaDesktop.setTheme(event.target.value))); document.querySelector('#display').addEventListener('change', event => { window.gammaDesktop.moveStage(event.target.value); setFeedback('Stage moved'); }); document.querySelector('#open-document').addEventListener('click', () => run('Opening…', () => window.gammaDesktop.openDocument())); document.querySelector('#save-document').addEventListener('click', () => run('Saving…', () => window.gammaDesktop.saveDocument())); document.querySelector('#present').addEventListener('click', () => { window.gammaDesktop.present(); setFeedback('Stage opened on the selected display'); });
document.querySelector('#set-countdown').addEventListener('click', () => run('Setting countdown…', () => window.gammaDesktop.countdown('set', Number(control.minutes.value)))); document.querySelector('#toggle-countdown').addEventListener('click', () => run('Updating countdown…', () => window.gammaDesktop.countdown(currentState.timing?.countdownRunning ? 'pause' : 'start'))); document.querySelector('#clear-countdown').addEventListener('click', () => run('Clearing countdown…', () => window.gammaDesktop.countdown('clear'))); document.querySelector('#send-cue').addEventListener('click', () => run('Showing speaker cue…', () => window.gammaDesktop.setCue(control.cue.value, 'normal'))); document.querySelector('#send-urgent-cue').addEventListener('click', () => run('Sending urgent cue…', () => window.gammaDesktop.setCue(control.cue.value, 'urgent'))); document.querySelector('#clear-cue').addEventListener('click', () => run('Clearing speaker cue…', () => window.gammaDesktop.clearCue())); document.querySelector('#run-copilot').addEventListener('click', () => run('Starting local co-pilot…', () => window.gammaDesktop.runCopilot(control.cli.value, document.querySelector('#copilot-prompt').value))); document.querySelector('#reveal-mcp-token').addEventListener('click', event => { const reveal = control.token.type === 'password'; control.token.type = reveal ? 'text' : 'password'; event.currentTarget.textContent = reveal ? 'Hide token' : 'Reveal token'; }); document.querySelector('#copy-mcp-config').addEventListener('click', async () => { const config = JSON.stringify({ mcpServers: { 'gamma-presenter': { url: control.endpoint.value, headers: { Authorization: `Bearer ${control.token.value}` } } } }, null, 2); try { await navigator.clipboard.writeText(config); setFeedback('MCP connection copied'); } catch { setFeedback('Clipboard access unavailable'); } });
control.operatorRequests.addEventListener('click', event => { const button = event.target.closest('[data-operator-request]'); if (!button) return; const approved = button.dataset.operatorDecision === 'approve'; run(approved ? 'Approving live action…' : 'Rejecting live action…', () => window.gammaDesktop.resolveOperatorAction(button.dataset.operatorRequest, approved)); });
document.querySelector('#focus-preview').addEventListener('click', event => { const active = document.body.classList.toggle('preview-focus'); event.currentTarget.setAttribute('aria-pressed', String(active)); event.currentTarget.textContent = active ? 'Return to editor' : 'Expand preview'; }); document.addEventListener('keydown', event => { if (!event.metaKey) return; if (event.key.toLowerCase() === 'o') { event.preventDefault(); run('Opening…', () => window.gammaDesktop.openDocument()); } if (event.key.toLowerCase() === 's') { event.preventDefault(); run('Saving…', () => window.gammaDesktop.saveDocument()); } if (event.key.toLowerCase() === 'd') { event.preventDefault(); document.body.classList.toggle('focus-mode'); } });
window.gammaDesktop.onState(applyState); applyState(await window.gammaDesktop.getSnapshot());
