import {test,expect} from '@playwright/test';
import {createServer} from 'node:http';
import {mkdirSync,writeFileSync} from 'node:fs';
import {browserHandler} from '../src/repository/browser.js';
import {studioBrowserJS,studioBrowserCSS} from '../src/engine/components/studio-browser.js';
let server,url,handler;const lifetimes=new Set();let slowEntered=false;
test.beforeAll(async()=>{handler=browserHandler({enabled:true});server=createServer(async(req,res)=>{const path=new URL(req.url,'http://localhost').pathname;if(await handler(req,res,path))return;if(path==='/lifetime'){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-store'});res.write('data: alive\n\n');lifetimes.add(res);res.on('close',()=>lifetimes.delete(res));return;}res.setHeader('Content-Type','text/html; charset=utf-8');if(path==='/slow'){slowEntered=true;await new Promise(r=>setTimeout(r,9000));}if(path==='/fixture'||path==='/next'||path==='/slow'){res.setHeader('X-Frame-Options','DENY');res.end(`<title>${path==='/next'?'Next page':'Moving browser'}</title><style>body{margin:0}canvas{display:block}input,button{font:24px sans-serif}</style><input><button onclick="document.title=document.querySelector('input').value">Apply</button><canvas width="1920" height="1000"></canvas><script>new EventSource('/lifetime');let c=document.querySelector('canvas'),x=c.getContext('2d'),n=0;function paint(){x.fillStyle=n++%60<30?'#ff2400':'#0040ff';x.fillRect(0,0,1920,1000);x.fillStyle='white';x.fillRect((n*20)%1800,100,120,500);requestAnimationFrame(paint)}paint();let a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=440;g.gain.value=.15;o.connect(g).connect(a.destination);o.start();a.resume();</script>`);return;}res.end(`<style>:root{--studio-panel:#141e30;--studio-ink:#f3f5f9;--studio-muted:#abb9d0;--studio-line:#405273;--studio-panel-raised:#213047;--studio-blue-soft:#6eafff}${studioBrowserCSS()}</style><body><script>window.Reveal={on(){}};${studioBrowserJS()}</script>`);});await new Promise(r=>server.listen(0,'127.0.0.1',r));url=`http://127.0.0.1:${server.address().port}`;});
test.afterAll(async()=>{await handler.close();await new Promise(r=>server.close(r));});
test('isolated browser streams moving 1080p video and real tab audio across navigation; closes tracks',{tag:'@capture-performance'},async({page})=>{
 test.setTimeout(90000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.evaluate(url=>window.dispatchEvent(new CustomEvent('gamma:browser-open',{detail:{url}})),url+'/fixture');await expect(page.locator('.gamma-browser-status')).toContainText('Moving browser',{timeout:20000});const video=page.locator('.gamma-browser-viewport video');await expect(video).toBeVisible();await page.waitForFunction(()=>document.querySelector('video')?.videoWidth===1920);await page.locator('[data-web=audio]').click();
 const proof=await video.evaluate(async v=>{
  const stream=v.srcObject,ctx=new AudioContext(),source=ctx.createMediaStreamSource(stream),analyser=ctx.createAnalyser();source.connect(analyser);await ctx.resume();const samples=new Float32Array(analyser.fftSize),start=v.getVideoPlaybackQuality().totalVideoFrames,begin=performance.now(),chunks=[];let maxRms=0;const recorder=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp8,opus',videoBitsPerSecond:6000000});recorder.ondataavailable=e=>chunks.push(e.data);recorder.start();
  const colors=[];const c=document.createElement('canvas');c.width=1;c.height=1;const x=c.getContext('2d');for(let i=0;i<24;i++){await new Promise(r=>setTimeout(r,100));analyser.getFloatTimeDomainData(samples);maxRms=Math.max(maxRms,Math.sqrt(samples.reduce((s,n)=>s+n*n,0)/samples.length));x.drawImage(v,1000,700,1,1,0,0,1,1);colors.push([...x.getImageData(0,0,1,1).data]);}
  const fps=(v.getVideoPlaybackQuality().totalVideoFrames-start)/(performance.now()-begin)*1000;const done=new Promise(r=>recorder.onstop=r);recorder.stop();await done;await ctx.close();const bytes=[...new Uint8Array(await new Blob(chunks).arrayBuffer())];return {width:v.videoWidth,height:v.videoHeight,fps,maxRms,colors,bytes};
 });
 mkdirSync('output/studio-review',{recursive:true});writeFileSync('output/studio-review/browser-stream.webm',Buffer.from(proof.bytes));delete proof.bytes;writeFileSync('output/studio-review/browser-stream-proof.json',JSON.stringify(proof,null,2));expect(proof.width).toBe(1920);expect(proof.height).toBe(1080);expect(proof.fps).toBeGreaterThan(24);expect(proof.maxRms).toBeGreaterThan(.03);expect(proof.colors.some(p=>p[0]>150&&p[2]<80)).toBe(true);expect(proof.colors.some(p=>p[2]>150&&p[0]<80)).toBe(true);
 const initial=await video.evaluate(v=>v.srcObject.getVideoTracks()[0].id);await page.getByLabel('Site address').fill(url+'/next');await page.getByRole('button',{name:'Open',exact:true}).click();await expect(page.locator('.gamma-browser-status')).toContainText('Next page');expect(await video.evaluate(v=>v.srcObject.getVideoTracks()[0].id)).toBe(initial);await video.click({position:{x:25,y:8}});await page.locator('[data-web-text]').fill('Typed in streaming browser');await page.locator('[data-web=text]').click();await page.locator('.gamma-browser-viewport').press('Tab');await page.locator('.gamma-browser-viewport').press('Enter');await expect(page.locator('.gamma-browser-status')).toContainText('Typed in streaming browser');
 await page.setViewportSize({width:390,height:844});await page.locator('[data-web=zoom]').click();await expect(video).toHaveCSS('width','1920px');await page.screenshot({path:'output/studio-review/mobile-browser-stream.png'});await page.evaluate(()=>window.beforeCloseTracks=__gammaBrowserStream.getTracks());await page.locator('[data-web=close]').click();await expect(page.locator('.gamma-browser')).toBeHidden();expect(await page.evaluate(()=>beforeCloseTracks.every(t=>t.readyState==='ended')&&__gammaBrowserStream===null)).toBe(true);expect(errors).toEqual([]);
 await page.evaluate(url=>window.dispatchEvent(new CustomEvent('gamma:browser-open',{detail:{url}})),url+'/fixture');await expect(page.locator('.gamma-browser-status')).toContainText('Moving browser',{timeout:20000});await page.waitForFunction(()=>document.querySelector('video')?.videoWidth===1920);await page.locator('[data-web=close]').click();
});

test('failed WebRTC negotiation releases its isolated tab and reconnects; endpoints reject foreign origins',async({page,request})=>{
 test.setTimeout(45000);await page.goto(url);await page.evaluate(url=>dispatchEvent(new CustomEvent('gamma:browser-open',{detail:{url}})),url+'/fixture');await expect(page.locator('.gamma-browser-status')).toContainText('Moving browser',{timeout:20000});await expect.poll(()=>lifetimes.size).toBe(1);const session=await (await request.get(url+'/__gamma/browser/session')).json();
 const route=url+'/__gamma/browser/stream';expect((await request.post(route,{headers:{'X-Gamma-Token':'wrong'},data:{type:'offer',sdp:'v=0'}})).status()).toBe(403);expect((await request.post(route,{headers:{'X-Gamma-Token':session.token,Origin:'https://untrusted.example'},data:{type:'offer',sdp:'v=0'}})).status()).toBe(403);expect((await request.post(route,{headers:{'X-Gamma-Token':session.token,'Sec-Fetch-Site':'cross-site'},data:{type:'offer',sdp:'v=0'}})).status()).toBe(403);
 expect((await request.post(route,{headers:{'X-Gamma-Token':session.token},data:{type:'offer',sdp:'deliberately malformed SDP'}})).status()).toBe(400);await expect.poll(()=>lifetimes.size).toBe(0);await page.locator('[data-web=close]').click();await page.evaluate(url=>dispatchEvent(new CustomEvent('gamma:browser-open',{detail:{url}})),url+'/fixture');await expect(page.locator('.gamma-browser-status')).toContainText('Moving browser',{timeout:20000});await expect.poll(()=>lifetimes.size).toBe(1);await page.locator('[data-web=close]').click();await expect.poll(()=>lifetimes.size).toBe(0);
});

test('closing the operator during navigation eventually releases the isolated browser',async({page,request})=>{
 test.setTimeout(45000);slowEntered=false;await page.goto(url);await page.evaluate(url=>dispatchEvent(new CustomEvent('gamma:browser-open',{detail:{url}})),url+'/fixture');await expect(page.locator('.gamma-browser-status')).toContainText('Moving browser',{timeout:20000});await expect.poll(()=>lifetimes.size).toBe(1);const {token}=await (await request.get(url+'/__gamma/browser/session')).json();const navigation=request.post(url+'/__gamma/browser',{headers:{'X-Gamma-Token':token},data:{action:'navigate',url:url+'/slow'}});await expect.poll(()=>slowEntered).toBe(true);await page.close();await navigation;await new Promise(r=>setTimeout(r,1000));await expect.poll(()=>lifetimes.size,{timeout:12000}).toBe(0);
});
