import {test,expect} from '@playwright/test';
import {createServer} from 'node:http';
import {mkdtempSync,writeFileSync,rmSync,mkdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {loadDeck} from '../src/loader/index.js';
import {renderDeck} from '../src/engine/renderer.js';
import {serveRepositoryPresentation} from '../src/repository/server.js';
let live,fixture,dir,url;
test.beforeAll(async()=>{dir=mkdtempSync(join(tmpdir(),'gamma-browser-broadcast-'));writeFileSync(join(dir,'index.html'),renderDeck(loadDeck(JSON.stringify({title:'Browser broadcast proof',slides:[{layout:'title',title:'Browser broadcast proof'}]}))));live=await serveRepositoryPresentation(dir,{port:0,browser:true});fixture=createServer((req,res)=>{res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('X-Frame-Options','DENY');res.end(`<title>${req.url==='/next'?'Next stream':'Live browser'}</title><style>body{margin:0}canvas{display:block}</style><canvas width="1920" height="1080"></canvas><script>const c=document.querySelector('canvas'),x=c.getContext('2d');let n=0;function frame(){x.fillStyle=n++%60<30?'#ff2400':'#0040ff';x.fillRect(0,0,1920,1080);x.fillStyle='white';x.fillRect((n*20)%1800,100,120,500);requestAnimationFrame(frame)}frame();const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=440;g.gain.value=.15;o.connect(g).connect(a.destination);o.start();a.resume();</script>`);});await new Promise(r=>fixture.listen(0,'127.0.0.1',r));url=`http://127.0.0.1:${fixture.address().port}`;});
test.afterAll(async()=>{await new Promise(r=>live.server.close(r));await new Promise(r=>fixture.close(r));rmSync(dir,{recursive:true,force:true});});
test('browser WebRTC reaches clean audience with one soundtrack, survives navigation and clears on close',async({page,context})=>{
 test.setTimeout(90000);page.setDefaultTimeout(15000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(live.url);await page.waitForFunction(()=>window.__GAMMA_READY__);await page.getByTestId('studio-skip').click();const popup=context.waitForEvent('page');await page.evaluate(()=>__gammaOpenOutput());let audience=await popup;audience.on('pageerror',e=>errors.push(e.message));await audience.waitForFunction(()=>window.__GAMMA_READY__);
 await page.evaluate(url=>dispatchEvent(new CustomEvent('gamma:browser-open',{detail:{url}})),url+'/');await expect(page.locator('.gamma-browser-status')).toContainText('Live browser');await page.waitForFunction(()=>document.querySelector('.gamma-browser video')?.videoWidth===1920);
 let output=audience.locator('.gamma-output-demo video');const monitor=page.locator('.gamma-browser video');await expect(output).not.toBeVisible();await page.evaluate(()=>__gammaOutputFlags.browser=true);await expect(output).toBeVisible();await expect.poll(()=>output.evaluate(v=>v.videoWidth)).toBe(1920);expect(await output.evaluate(v=>v.muted)).toBe(true);
 // The preference must not briefly unmute both monitors in the same interaction.
 const immediateMuted=await page.evaluate(()=>{document.querySelector('[data-web=audio]').click();return document.querySelector('.gamma-browser video').muted;});
 await expect.poll(()=>monitor.evaluate(v=>v.muted)).toBe(true);await expect.poll(()=>output.evaluate(v=>v.muted)).toBe(false);await audience.evaluate(()=>__gammaResumeOutputAudio());
 const proof=await output.evaluate(async v=>{await v.play();const a=new AudioContext(),source=a.createMediaStreamSource(v.srcObject),analyser=a.createAnalyser();source.connect(analyser);await a.resume();const data=new Float32Array(analyser.fftSize),start=v.getVideoPlaybackQuality().totalVideoFrames,begin=performance.now(),chunks=[];const recorder=new MediaRecorder(v.srcObject,{mimeType:'video/webm;codecs=vp8,opus'});recorder.ondataavailable=e=>chunks.push(e.data);recorder.start();let rms=0;for(let i=0;i<20;i++){await new Promise(r=>setTimeout(r,100));analyser.getFloatTimeDomainData(data);rms=Math.max(rms,Math.sqrt(data.reduce((n,x)=>n+x*x,0)/data.length));}const fps=(v.getVideoPlaybackQuality().totalVideoFrames-start)/(performance.now()-begin)*1000;const done=new Promise(r=>recorder.onstop=r);recorder.stop();await done;await a.close();return {width:v.videoWidth,height:v.videoHeight,fps,rms,bytes:[...new Uint8Array(await new Blob(chunks).arrayBuffer())]};});
 mkdirSync('output/studio-review',{recursive:true});writeFileSync('output/studio-review/browser-broadcast.webm',Buffer.from(proof.bytes));delete proof.bytes;proof.immediateMuted=immediateMuted;writeFileSync('output/studio-review/browser-broadcast-proof.json',JSON.stringify(proof,null,2));expect(proof.width).toBe(1920);expect(proof.height).toBe(1080);expect(proof.rms).toBeGreaterThan(.03);expect(proof.fps).toBeGreaterThan(24);for(const selector of ['.gamma-browser','.gamma-orbit','.gamma-studio-live'])await expect(audience.locator(selector)).not.toBeVisible();await audience.screenshot({path:'output/studio-review/browser-broadcast-audience.png'});
 const track=await output.evaluate(v=>v.srcObject.getVideoTracks()[0].id);await page.getByLabel('Site address').fill(url+'/next');await page.getByRole('button',{name:'Open',exact:true}).click();await expect(page.locator('.gamma-browser-status')).toContainText('Next stream');expect(await output.evaluate(v=>v.srcObject.getVideoTracks()[0].id)).toBe(track);
 await page.evaluate(()=>__gammaOutputFlags.browser=false);await expect(output).not.toBeVisible();await expect.poll(()=>monitor.evaluate(v=>v.muted)).toBe(false);expect(await output.evaluate(v=>v.paused&&v.srcObject===null)).toBe(true);
 await page.evaluate(()=>__gammaOutputFlags.browser=true);await expect(output).toBeVisible();await expect.poll(()=>monitor.evaluate(v=>v.muted)).toBe(true);await expect.poll(()=>output.evaluate(v=>v.muted)).toBe(false);
 await audience.close();await expect.poll(()=>monitor.evaluate(v=>v.muted)).toBe(false);expect(await monitor.evaluate(v=>v.srcObject.getVideoTracks()[0].readyState)).toBe('live');
 const reopened=context.waitForEvent('page');await page.evaluate(()=>__gammaOpenOutput());audience=await reopened;await audience.waitForFunction(()=>window.__GAMMA_READY__);output=audience.locator('.gamma-output-demo video');await expect(output).toBeVisible();await expect.poll(()=>monitor.evaluate(v=>v.muted)).toBe(true);await expect.poll(()=>output.evaluate(v=>v.muted)).toBe(false);
 await page.locator('[data-web=audio]').click();await expect.poll(()=>output.evaluate(v=>v.muted)).toBe(true);await page.locator('[data-web=close]').click();await expect(output).not.toBeVisible();expect(await output.evaluate(v=>v.srcObject===null&&v.paused)).toBe(true);await audience.close();expect(errors).toEqual([]);expect(immediateMuted,'Operator monitoring must remain muted while audience audio is enabled').toBe(true);
});
