import {test,expect} from '@playwright/test';
import {mkdtempSync,writeFileSync,rmSync,mkdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {createServer} from 'node:http';
import {loadDeck} from '../src/loader/index.js';
import {renderDeck} from '../src/engine/renderer.js';
import {serveRepositoryPresentation} from '../src/repository/server.js';
import {presentationContrast} from '../src/repository/contrast.js';
let live,dir,fixture;const evidence=resolve('output/studio-review');
test.beforeAll(async()=>{mkdirSync(evidence,{recursive:true});dir=mkdtempSync(join(tmpdir(),'gamma-demo-'));writeFileSync(join(dir,'index.html'),renderDeck(loadDeck('presentations/studio-demo.yaml')));live=await serveRepositoryPresentation(dir,{port:0,terminal:true,browser:true});fixture=createServer((q,r)=>{r.setHeader('Content-Type','text/html');r.setHeader('X-Frame-Options','DENY');r.end('<title>Interactive browser</title><style>body{font:24px sans-serif}input,button{font:24px sans-serif}</style><input aria-label="Test"><button onclick="document.title=document.querySelector(\'input\').value">Apply</button><div style="height:2000px">Page content</div><p>Bottom</p>');});await new Promise(r=>fixture.listen(0,'127.0.0.1',r));});
test.afterAll(async()=>{await new Promise(r=>live.server.close(r));await new Promise(r=>fixture.close(r));rmSync(dir,{recursive:true,force:true});});
const open=async p=>{await p.goto(live.url+'?theme=signal-room');await p.waitForFunction(()=>window.__GAMMA_READY__);};
for(const [name,size] of [['desktop',{width:1440,height:900}],['tablet',{width:834,height:1194}],['mobile',{width:390,height:844}]])test(`47 slides: render, contrast and assets ${name}`,async({page})=>{
 test.setTimeout(180000);await page.setViewportSize(size);await page.emulateMedia({reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));await open(page);const failures=[];const captures=join(evidence,name);mkdirSync(captures,{recursive:true});
 for(let i=0;i<47;i++){await page.evaluate(i=>Reveal.slide(i),i);await page.waitForTimeout(180);if(i>=2&&i<=6)await page.waitForSelector('section.present .archify-slide[data-ready=true]');await page.evaluate(()=>document.getAnimations().forEach(a=>{if(a.effect.getComputedTiming().iterations!==Infinity)a.finish();}));const checks=await page.evaluate(presentationContrast);if(checks.failures.length)failures.push({slide:i+1,failures:checks.failures});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.locator('section.present img').evaluateAll(images=>Promise.all(images.map(img=>img.decode())));await page.screenshot({path:join(captures,String(i+1).padStart(2,'0')+'.png')});}
 writeFileSync(join(evidence,name+'-manifest.json'),JSON.stringify({slides:47,size,errors,failures},null,2));expect(errors).toEqual([]);expect(failures).toEqual([]);
});
test('browser typing, navigation, movable frame and zoom work from visible controls',async({page})=>{await open(page);await page.locator('.gamma-orbit-hub').click();await page.locator('[data-orbit=studio]').click();await page.getByText('Demonstrations',{exact:true}).click();await page.locator('[data-live=browser]').click();const web=page.locator('.gamma-browser');await web.getByLabel('Site address').fill(`http://127.0.0.1:${fixture.address().port}/`);await web.getByRole('button',{name:'Open',exact:true}).click();await expect(web.locator('video')).toBeVisible();await expect(web.getByRole('status')).toContainText('Interactive browser');const before=await web.boundingBox();await web.getByTestId('studio-browser-drag').dragTo(page.locator('.gamma-browser-status'));const moved=await web.boundingBox();expect(moved.x).not.toBe(before.x);await web.locator('video').click({position:{x:40,y:20}});await web.locator('[data-web-text]').fill('Browser validated');await web.locator('[data-web=text]').click();await web.locator('.gamma-browser-viewport').press('Tab');await web.locator('.gamma-browser-viewport').press('Enter');await expect(web.getByRole('status')).toContainText('Browser validated');await page.setViewportSize({width:390,height:844});await web.locator('[data-web=zoom]').click();await expect(web.locator('video')).toHaveCSS('width','1920px');await page.screenshot({path:join(evidence,'mobile-browser.png')});await web.locator('[data-web=expand]').click();await expect(web).toHaveClass(/is-expanded/);await web.locator('[data-web=close]').click();await expect(web).not.toBeVisible();});
test('audience mirrors chart tooltip, GPU canvas and media with one soundtrack',async({page,context})=>{
 test.setTimeout(90000);await open(page);const errors=[];page.on('pageerror',e=>errors.push(e.message));const popup=context.waitForEvent('page');await page.evaluate(()=>__gammaOpenOutput());const audience=await popup;audience.on('pageerror',e=>errors.push(e.message));await audience.waitForFunction(()=>window.__GAMMA_READY__);await page.evaluate(()=>Reveal.slide(12));await page.waitForFunction(()=>{const el=document.querySelector('section.present [id^=chart_]');return el&&echarts.getInstanceByDom(el);});await page.evaluate(()=>echarts.getInstanceByDom(document.querySelector('section.present [id^=chart_]')).dispatchAction({type:'showTip',seriesIndex:0,dataIndex:0}));await expect(audience.locator('.gamma-output-tooltip')).toContainText('Revenue');
 await page.evaluate(()=>Reveal.slide(8));await page.locator('.gamma-orbit-hub').click();await page.locator('[data-orbit=actions]').click();await page.locator('.gamma-orbit-panel').getByRole('button',{name:'Play media',exact:true}).click();await expect.poll(()=>audience.locator('.studio-slide-media').evaluate(m=>!m.paused&&m.currentTime>.2)).toBe(true);expect(await page.locator('.studio-slide-media').evaluate(m=>m.muted)).toBe(true);expect(await audience.locator('.studio-slide-media').evaluate(m=>m.muted)).toBe(false);await page.locator('.gamma-orbit-panel').getByRole('button',{name:'Mute media audio',exact:true}).click();await expect.poll(()=>audience.locator('.studio-slide-media').evaluate(m=>m.muted)).toBe(true);
 const gpu=await page.evaluate(()=>[...document.querySelectorAll('.reveal .slides>section')].findIndex(s=>s.querySelector('.d3-webgpu-stage')));expect(gpu).toBeGreaterThan(-1);await page.evaluate(i=>Reveal.slide(i),gpu);await expect(audience.locator('section.present .d3-webgpu-stage')).toBeVisible();const mirror=audience.locator('section.present canvas.gamma-output-canvas').first();await expect(mirror).toBeVisible();await expect(audience.locator('section.present .d3-webgpu-canvas')).toHaveCSS('visibility','hidden');const pixels=canvas=>{const data=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;let gold=0,blue=0;for(let i=0;i<data.length;i+=4){const r=data[i],g=data[i+1],b=data[i+2];if(r>150&&g>70&&g<220&&b<70)gold++;if(b>150&&b>r*1.15&&g>80)blue++;}return {width:canvas.width,height:canvas.height,gold,blue};};await expect.poll(()=>mirror.evaluate(canvas=>{const data=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;let gold=0,blue=0;for(let i=0;i<data.length;i+=4){const r=data[i],g=data[i+1],b=data[i+2];if(r>150&&g>70&&g<220&&b<70)gold++;if(b>150&&b>r*1.15&&g>80)blue++;}return gold>5000&&blue>3000;}),{timeout:8000}).toBe(true);const motion=await mirror.evaluate(pixels);expect(motion.width).toBeGreaterThan(100);expect(motion.gold).toBeGreaterThan(5000);expect(motion.blue).toBeGreaterThan(3000);await audience.screenshot({path:join(evidence,'clean-gpu.png')});expect(errors).toEqual([]);await audience.close();
});
