import {findBrowserExecutable} from '../src/browser.js';
import {test,expect,chromium} from '@playwright/test';
import {mkdtempSync,writeFileSync,rmSync,readFileSync,mkdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {execFileSync} from 'node:child_process';
import {loadDeck} from '../src/loader/index.js';
import {renderDeck} from '../src/engine/renderer.js';
import {serveRepositoryPresentation} from '../src/repository/server.js';
let live,dir;const evidence=resolve('output/studio-review');
test.beforeAll(async()=>{mkdirSync(evidence,{recursive:true});dir=mkdtempSync(join(tmpdir(),'gamma-studio-'));writeFileSync(join(dir,'index.html'),renderDeck(loadDeck('presentations/repository-review.yaml')));live=await serveRepositoryPresentation(dir,{port:0,terminal:true,browser:true});});
test.afterAll(async()=>{await new Promise(r=>live.server.close(r));rmSync(dir,{recursive:true,force:true});});
async function synthetic(page){await page.addInitScript(()=>{
 const makeVideo=(color,w,h)=>{const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');const draw=()=>{ctx.fillStyle=color;ctx.fillRect(0,0,w,h);ctx.fillStyle='#ffffff';ctx.fillRect((Date.now()/10)%w,h-10,8,8);};draw();setInterval(draw,33);return c.captureStream(30);};
 window.qaTracks=[];
 Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:async opts=>{const stream=new MediaStream();if(opts.video)makeVideo('#00ff00',320,200).getVideoTracks().forEach(t=>stream.addTrack(t));if(opts.audio){const a=new AudioContext(),osc=a.createOscillator(),gain=a.createGain(),dest=a.createMediaStreamDestination();gain.gain.value=.3;osc.connect(gain);gain.connect(dest);osc.start();await a.resume();dest.stream.getAudioTracks().forEach(t=>stream.addTrack(t));}qaTracks.push(...stream.getTracks());return stream;}});
 const realDisplay=navigator.mediaDevices.getDisplayMedia.bind(navigator.mediaDevices);Object.defineProperty(navigator.mediaDevices,'getDisplayMedia',{value:async options=>{if(window.qaRealDisplay)return realDisplay(options);window.qaDisplay=makeVideo('#183055',1280,720);return qaDisplay;}});
 window.showSaveFilePicker=undefined;
 });}
async function open(page){await page.goto(live.url+'?theme=signal-room');await page.waitForFunction(()=>window.__GAMMA_READY__&&window.__gammaStudio);}
async function studio(page){await page.locator('.gamma-orbit-hub').click();await page.locator('[data-orbit=studio]').click();await expect(page.locator('.gamma-live-panel')).toBeVisible();}
test('real encoded take: independent tracks, pause, mute, camera, retained download',async({page})=>{
 test.setTimeout(90000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await synthetic(page);await open(page);await studio(page);
 await page.locator('[data-live=camera]').click();await page.locator('[data-live=microphone]').click();await expect.poll(()=>page.evaluate(()=>__gammaStudio.snapshot().microphone)).toBe(true);
 const cameraTrack=await page.evaluate(()=>qaTracks.find(t=>t.kind==='video').id);await page.locator('[data-live=microphone]').click();expect(await page.evaluate(()=>qaTracks.find(t=>t.kind==='video').readyState)).toBe('live');await page.locator('[data-live=microphone]').click();expect(await page.evaluate(()=>qaTracks.find(t=>t.kind==='video').id)).toBe(cameraTrack);
 await page.getByText('Composition et sources',{exact:true}).click();await page.locator('[data-live-setting=captureMode]').selectOption('external');await page.locator('[data-live=source]').click();await page.locator('[data-live=record]').click();await expect(page.getByTestId('studio-recording-controls')).toBeVisible();const start=Date.now();await page.waitForTimeout(1800);
 await page.locator('[data-action=live-mic]').click();const muted=(Date.now()-start)/1000;await page.waitForTimeout(2500);await page.locator('[data-action=live-mic]').click();await page.waitForTimeout(1400);
 await page.getByTestId('studio-pause').click();await expect.poll(()=>page.evaluate(()=>__gammaStudio.snapshot().phase)).toBe('paused');const counter=await page.locator('.gamma-recording-badge b').innerText();await page.waitForTimeout(1500);expect(await page.locator('.gamma-recording-badge b').innerText()).toBe(counter);
 await studio(page);await expect(page.locator('[data-live=configure]')).toBeDisabled();await page.locator('[data-live=close]').click();await page.getByTestId('studio-pause').click();await expect.poll(()=>page.evaluate(()=>__gammaStudio.snapshot().phase)).toBe('recording');
 await page.locator('[data-action=live-camera]').click();await page.waitForTimeout(1300);await page.locator('[data-action=live-camera]').click();await page.waitForTimeout(800);await page.getByTestId('studio-stop').click();await expect(page.getByTestId('studio-recording-review')).toBeVisible();await expect(page.locator('[data-review-video]')).toHaveJSProperty('readyState',4);
 const bytes=await page.evaluate(async()=>Array.from(new Uint8Array(await (await fetch(document.querySelector('[data-review-video]').src)).arrayBuffer())));const type=await page.evaluate(()=>document.querySelector('[data-review-filename]').textContent);const file=join(evidence,type);writeFileSync(file,Buffer.from(bytes));
 const probe=JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-show_format','-of','json',file],{encoding:'utf8'}));const video=probe.streams.find(s=>s.codec_type==='video');expect([video.width,video.height]).toEqual([1280,720]);expect(probe.streams.some(s=>s.codec_type==='audio')).toBe(true);expect(+probe.format.duration).toBeGreaterThan(7);expect(+probe.format.duration).toBeLessThan((Date.now()-start)/1000-1);
 const pcm=execFileSync('ffmpeg',['-v','error','-i',file,'-vn','-ac','1','-ar','48000','-f','f32le','pipe:1'],{maxBuffer:10000000});const rms=(from,length)=>{let sum=0,n=0;for(let i=Math.floor(from*48000);i<Math.min(pcm.length/4,(from+length)*48000);i++){sum+=pcm.readFloatLE(i*4)**2;n++;}return Math.sqrt(sum/n);};expect(rms(.5,.6)).toBeGreaterThan(.04);expect(rms(muted+.5,1)).toBeLessThan(.003);expect(rms(muted+3,.5)).toBeGreaterThan(.04);
 for(const [name,at] of [['camera-visible',.6],['camera-hidden',6.4]])execFileSync('ffmpeg',['-v','error','-y','-ss',String(at),'-i',file,'-frames:v','1',join(evidence,name+'.png')]);
 const pixels=at=>execFileSync('ffmpeg',['-v','error','-ss',String(at),'-i',file,'-frames:v','1','-f','rawvideo','-pix_fmt','rgb24','pipe:1'],{maxBuffer:5000000});const green=buffer=>{let n=0;for(let i=0;i<buffer.length;i+=3)if(buffer[i+1]>180&&buffer[i]<70&&buffer[i+2]<70)n++;return n;};expect(green(pixels(.6))).toBeGreaterThan(10000);expect(green(pixels(6.4))).toBeLessThan(100);
 writeFileSync(join(evidence,'recording-proof.json'),JSON.stringify({file,type,probe,audioRMS:{audible:rms(.5,.6),muted:rms(muted+.5,1)},errors},null,2));
 await page.locator('[data-review-action=back]').click();await studio(page);await expect(page.locator('.gamma-live-take')).toBeVisible();await page.locator('[data-live=review]').click();const download=page.waitForEvent('download');await page.getByTestId('studio-review-save').click();await download;expect(await page.evaluate(()=>__gammaStudio.snapshot().lastRecording.saved)).toBe(false);await page.locator('[data-review-action=confirm-save]').click();expect(await page.evaluate(()=>__gammaStudio.snapshot().lastRecording.saved)).toBe(true);expect(errors).toEqual([]);
});
for(const [name,size] of [['desktop',{width:1440,height:900}],['tablet',{width:834,height:1194}],['mobile',{width:390,height:844}]])test(`studio layout and camera keyboard ${name}`,async({page})=>{
 await page.setViewportSize(size);await synthetic(page);await open(page);await studio(page);await page.locator('[data-live=camera]').click();await page.screenshot({path:join(evidence,name+'-studio.png')});await page.locator('[data-live=close]').click();const drag=page.getByTestId('studio-camera-drag');await drag.press('ArrowRight');const handle=page.getByLabel('Redimensionner la caméra');const before=await page.locator('.gamma-camera').boundingBox();await handle.press('ArrowRight');expect((await page.locator('.gamma-camera').boundingBox()).width).toBeGreaterThan(before.width);await page.setViewportSize({width:390,height:660});const r=await page.locator('.gamma-camera').boundingBox();expect(r.x).toBeGreaterThanOrEqual(0);expect(r.x+r.width).toBeLessThanOrEqual(391);expect(r.y+r.height).toBeLessThanOrEqual(660);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('clean audience: no operator controls, theme, camera and explicit demo broadcasting',async({page,context})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await synthetic(page);await open(page);await page.evaluate(()=>applyPresentationTheme('analyst-proof',{animate:false}));await studio(page);await page.locator('[data-live=camera]').click();const popup=context.waitForEvent('page');await page.locator('[data-live=output-window]').click();const audience=await popup;audience.on('pageerror',e=>errors.push(e.message));await audience.waitForFunction(()=>window.__GAMMA_READY__);await expect(audience.locator('body')).toHaveAttribute('data-presentation-theme','analyst-proof');await expect(audience.locator('.gamma-orbit')).toHaveCount(0);await expect(audience.locator('.gamma-output-camera')).toBeVisible();
 await page.locator('[data-live=source]').click();expect(await page.evaluate(()=>__gammaStudio.snapshot().screen)).toBe(false);await expect(page.getByTestId('studio-notice')).toContainText('refusée');
 await page.locator('[data-live=close]').click();await page.evaluate(()=>Reveal.slide(5));await expect(audience.locator('section.present')).toHaveAttribute('data-slide-number','06');await page.waitForSelector('.archify-slide[data-ready=true]');await audience.waitForSelector('.archify-slide[data-ready=true]');
 await page.evaluate(()=>window.__gammaArchify.states.find(s=>s.section===Reveal.getCurrentSlide()).frame.contentWindow.postMessage({channel:'gamma-archify',action:'node',value:'mcp'},'*'));await expect.poll(async()=>{const svgs=await Promise.all([page,audience].map(p=>p.frames().find(f=>f.parentFrame()).locator('svg').first().innerHTML()));return svgs[0]===svgs[1];},{timeout:8000}).toBe(true);
 await page.locator('.gamma-orbit-hub').click();await page.locator('[data-orbit=full]').click();await expect(audience.locator('.archify-fullscreen')).toBeVisible();await expect(page.locator('.archify-fullscreen .gamma-camera')).toBeVisible();await expect(audience.locator('.archify-fullscreen .gamma-output-camera')).toBeVisible();
 await audience.screenshot({path:join(evidence,'clean-architecture.png')});await page.locator('.gamma-orbit-hub').press('Escape');await page.locator('.gamma-orbit-hub').press('Escape');
 await studio(page);await page.getByText('Démonstrations',{exact:true}).click();await page.locator('[data-live=terminal]').click();await expect(page.getByTestId('studio-terminal')).toBeVisible();await expect(audience.locator('pre.gamma-output-demo')).not.toBeVisible();await page.evaluate(()=>window.__gammaOutputFlags.terminal=true);await expect(audience.locator('pre.gamma-output-demo')).toBeVisible();await expect(audience.locator('.gamma-terminal')).toHaveCount(0);expect(errors).toEqual([]);await audience.close();
});
test('real clean tab recording excludes operator UI from decoded video',async()=>{
 test.setTimeout(90000);const realDir=join(dir,'real-clean');mkdirSync(realDir);writeFileSync(join(realDir,'index.html'),renderDeck(loadDeck('presentations/studio-demo.yaml')));const realLive=await serveRepositoryPresentation(realDir,{port:0});const profile=mkdtempSync(join(tmpdir(),'gamma-clean-profile-'));const context=await chromium.launchPersistentContext(profile,{executablePath:findBrowserExecutable(),headless:true,viewport:{width:1440,height:900},args:['--auto-select-tab-capture-source-by-title=SORTIE','--autoplay-policy=no-user-gesture-required']});
 try{const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await synthetic(page);await page.goto(realLive.url+'?theme=signal-room');await page.waitForFunction(()=>window.__GAMMA_READY__);await page.evaluate(()=>window.qaRealDisplay=true);await studio(page);await page.locator('[data-live=camera]').click();await page.locator('[data-live=microphone]').click();await page.getByText('Composition et sources',{exact:true}).click();await page.locator('[data-live-setting=output]').selectOption('landscape');const popup=context.waitForEvent('page');await page.locator('[data-live=output-window]').click();const audience=await popup;audience.on('pageerror',e=>errors.push(e.message));await audience.waitForFunction(()=>window.__GAMMA_READY__);const cdp=await context.newCDPSession(audience),win=await cdp.send('Browser.getWindowForTarget');await cdp.send('Browser.setWindowBounds',{windowId:win.windowId,bounds:{width:1920,height:1080}});await audience.setViewportSize({width:1920,height:1080});await cdp.detach();await page.bringToFront();await page.locator('[data-live=source]').click();await expect.poll(()=>page.evaluate(()=>__gammaStudio.snapshot().screen)).toBe(true);const source=await page.evaluate(()=>__gammaStudio.snapshot().sourceSettings);expect(source.width).toBeGreaterThanOrEqual(1920);expect(source.height).toBeGreaterThanOrEqual(1080);await page.locator('[data-live=record]').click();await expect.poll(()=>page.evaluate(()=>__gammaStudio.snapshot().phase)).toBe('recording');await expect(page.getByTestId('studio-recording-controls')).toBeVisible();
 await page.evaluate(()=>{const sentinel=document.createElement('div');sentinel.id='operator-canary';sentinel.style.cssText='position:fixed;left:350px;top:180px;width:400px;height:180px;background:#ff00ff;z-index:500';sentinel.textContent='COMMANDES OPÉRATEUR HORS VIDÉO';document.body.append(sentinel);});await studio(page);await page.waitForTimeout(2200);await page.screenshot({path:join(evidence,'clean-recording-operator.png')});await audience.screenshot({path:join(evidence,'clean-recording-audience.png')});expect(await page.evaluate(()=>({phase:__gammaStudio.snapshot().phase,notice:document.querySelector('[data-testid=studio-notice]')?.textContent}))).toMatchObject({phase:'recording'});await page.locator('[data-live=close]').click();await page.getByTestId('studio-pause').click();await page.waitForTimeout(1200);await page.getByTestId('studio-pause').click();await page.waitForTimeout(1200);await page.getByTestId('studio-stop').click();await expect(page.getByTestId('studio-recording-review')).toBeVisible();const bytes=await page.evaluate(async()=>Array.from(new Uint8Array(await (await fetch(document.querySelector('[data-review-video]').src)).arrayBuffer())));const file=join(evidence,'clean-real-capture.mp4');writeFileSync(file,Buffer.from(bytes));const probe=JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-show_format','-of','json',file],{encoding:'utf8'}));const pixels=execFileSync('ffmpeg',['-v','error','-ss','1.5','-i',file,'-frames:v','1','-f','rawvideo','-pix_fmt','rgb24','pipe:1'],{maxBuffer:12000000});let magenta=0,green=0,ribbonPixels=0;const dimensions=probe.streams.find(s=>s.codec_type==='video');for(let i=0;i<pixels.length;i+=3){const x=(i/3)%dimensions.width,y=Math.floor(i/3/dimensions.width);if(x>dimensions.width*.5&&y>dimensions.height*.22&&y<dimensions.height*.58&&Math.max(pixels[i],pixels[i+1],pixels[i+2])-Math.min(pixels[i],pixels[i+1],pixels[i+2])>60&&Math.max(pixels[i],pixels[i+1],pixels[i+2])>100)ribbonPixels++;if(pixels[i]>180&&pixels[i+1]<80&&pixels[i+2]>180)magenta++;if(pixels[i]<80&&pixels[i+1]>180&&pixels[i+2]<80)green++;}expect(magenta).toBeLessThan(50);expect(green).toBeGreaterThan(5000);expect(ribbonPixels).toBeGreaterThan(5000);execFileSync('ffmpeg',['-v','error','-y','-ss','1.5','-i',file,'-frames:v','1',join(evidence,'clean-decoded.png')]);writeFileSync(join(evidence,'clean-proof.json'),JSON.stringify({source:'Real Chrome tab via getDisplayMedia, persistent temporary profile; synthetic camera and microphone only',file,probe,magenta,green,ribbonPixels,errors},null,2));expect(errors).toEqual([]);
 }finally{await context.close();await new Promise(r=>realLive.server.close(r));rmSync(profile,{recursive:true,force:true});}
});
