import {test,expect} from '@playwright/test';
import {createServer} from 'node:http';
import {mkdtempSync,writeFileSync,readFileSync,rmSync,mkdirSync,appendFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {chromium} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import {findBrowserExecutable} from '../src/browser.js';
import {loadDeck} from '../src/loader/index.js';
import {renderDeck} from '../src/engine/renderer.js';
let server,base,dir;const evidence=resolve('output/studio-production');
test.beforeAll(async()=>{dir=mkdtempSync(join(tmpdir(),'gamma-production-'));mkdirSync(evidence,{recursive:true});const html=renderDeck(loadDeck('presentations/youtube-pilot.yaml'));server=createServer(async(req,res)=>{if(req.url==='/__qa/export'&&req.method==='POST'){for await(const bytes of req)appendFileSync(join(evidence,'endurance.mp4'),bytes);res.end('ok');return;}res.setHeader('Content-Type','text/html');res.end(html);});await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}/`;});
test.afterAll(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
async function sources(page,{width=1280,height=720,real=false}={}){
 await page.addInitScript(({width,height,real})=>{
  const native=navigator.mediaDevices.getDisplayMedia.bind(navigator.mediaDevices);
  const makeVideo=(w,h)=>{const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');let tick=0;setInterval(()=>{x.fillStyle=tick++%2?'#00ed00':'#003300';x.fillRect(0,0,w,h);x.fillStyle='#fff';x.fillRect((tick*7)%w,0,20,h);},33);return c.captureStream(30);};
  const ac=new AudioContext(),osc=ac.createOscillator(),gain=ac.createGain(),out=ac.createMediaStreamDestination();osc.frequency.value=440;gain.gain.value=.2;osc.connect(gain).connect(out);osc.start();
  Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:async c=>{await ac.resume();const s=new MediaStream();if(c.video)s.addTrack(makeVideo(320,180).getVideoTracks()[0]);if(c.audio)s.addTrack(out.stream.getAudioTracks()[0].clone());return s;}});
  Object.defineProperty(navigator.mediaDevices,'getDisplayMedia',{value:async c=>real?native(c):makeVideo(width,height)});
  Object.defineProperty(navigator.mediaDevices,'enumerateDevices',{value:async()=>[{kind:'audioinput',deviceId:'mic-a',label:'Mic A'},{kind:'audioinput',deviceId:'mic-b',label:'Mic B'},{kind:'videoinput',deviceId:'cam-a',label:'Camera A'},{kind:'videoinput',deviceId:'cam-b',label:'Camera B'}]});
 },{width,height,real});
}
const open=async page=>{await page.goto(base);await page.waitForFunction(()=>window.__GAMMA_READY__);};
const studio=async page=>{await page.locator('.gamma-orbit-hub').click();await page.locator('[data-orbit=studio]').click();};
test('fixed resolution refuses smaller source and offers explicit source profile',async({page})=>{
 await sources(page,{width:640,height:360});await open(page);await studio(page);await page.getByText('Composition and sources',{exact:true}).click();await page.locator('[data-live-setting=captureMode]').selectOption('external');await page.locator('[data-live-setting=output]').selectOption('landscape');await page.locator('[data-live=source]').click();await expect(page.locator('.gamma-production-quality')).toContainText('640 × 360');await expect(page.locator('[data-live=record]')).toBeDisabled();await page.evaluate(()=>__gammaStudio.record());await expect(page.locator('.gamma-studio-notice')).toContainText('Source 640 × 360 is too small for 1920 × 1080. Enlarge output or choose Source dimensions.');expect(await page.evaluate(()=>__gammaStudio.snapshot().phase)).toBe('ready');await page.locator('[data-live-setting=output]').selectOption('source');expect(await page.evaluate(()=>__gammaStudio.snapshot().output)).toBe('source');
});
test('production mix, device replacement while paused and durable review after reload',async({page})=>{
 test.setTimeout(60000);await sources(page);await open(page);await studio(page);await page.locator('[data-live=camera]').click();await page.locator('[data-live=microphone]').click();await page.getByText('Composition and sources',{exact:true}).click();await page.locator('[data-live-setting=captureMode]').selectOption('external');await page.locator('[data-live=source]').click();await page.getByText('Program audio',{exact:true}).click();await page.getByLabel('Volume voice',{exact:true}).fill('60');await page.getByLabel('Lower media while I speak',{exact:true}).check();expect(await page.evaluate(()=>__gammaStudio.snapshot().audio)).toMatchObject({micGain:.6,ducking:true});await page.locator('[data-live=record]').click();await expect.poll(()=>page.evaluate(()=>__gammaStudio.snapshot().storage?.bytes||0)).toBeGreaterThan(1000);await page.getByTestId('studio-pause').click();await studio(page);await page.getByText('Devices',{exact:true}).click();await page.getByLabel('Studio microphone',{exact:true}).selectOption('mic-b');await page.getByLabel('Studio camera',{exact:true}).selectOption('cam-b');expect(await page.evaluate(()=>__gammaStudio.snapshot())).toMatchObject({phase:'paused',devices:{micId:'mic-b',cameraId:'cam-b'},microphone:true});await page.locator('[data-live=close]').click();await page.getByTestId('studio-pause').click();await page.waitForTimeout(1500);await page.getByTestId('studio-stop').click();await expect(page.getByTestId('studio-recording-review')).toBeVisible();await page.evaluate(()=>window.onbeforeunload=null);page.on('dialog',d=>d.accept());await page.reload();await page.waitForFunction(()=>window.__GAMMA_READY__);await studio(page);await expect(page.locator('.gamma-production-take')).toHaveCount(1);await page.getByRole('button',{name:'Review / recover'}).click();await expect(page.locator('[data-review-video]')).toHaveJSProperty('readyState',4);
});
test('authored scene hides only camera and restores it on next scene',async({page})=>{
 await sources(page);await open(page);await studio(page);await page.locator('[data-live=camera]').click();await page.locator('[data-live=microphone]').click();const hidden=await page.evaluate(()=>__gammaScenes.findIndex(s=>s?.camera?.visible===false)),shown=await page.evaluate(()=>__gammaScenes.findIndex(s=>s?.camera?.visible===true));expect(hidden).toBeGreaterThan(-1);expect(shown).toBeGreaterThan(-1);await page.evaluate(i=>Reveal.slide(i),hidden);expect(await page.evaluate(()=>__gammaStudio.snapshot())).toMatchObject({camera:false,microphone:true});await page.evaluate(i=>Reveal.slide(i),shown);expect(await page.evaluate(()=>__gammaStudio.snapshot())).toMatchObject({camera:true,microphone:true});
});
test('native clean capture endurance with durable fragments',async()=>{
 const seconds=Number(process.env.GAMMA_ENDURANCE_SECONDS||0);test.skip(seconds<10,'Opt-in: GAMMA_ENDURANCE_SECONDS=900');test.setTimeout((seconds+100)*1000);
 const profile=mkdtempSync(join(tmpdir(),'gamma-endurance-')),context=await chromium.launchPersistentContext(profile,{executablePath:findBrowserExecutable(),headless:true,viewport:{width:1920,height:1080},args:['--auto-select-tab-capture-source-by-title=VIDEO OUTPUT','--autoplay-policy=no-user-gesture-required']});
 try{const page=await context.newPage();await sources(page,{real:true});await open(page);await studio(page);await page.locator('[data-live=camera]').click();await page.locator('[data-live=microphone]').click();await page.getByText('Composition and sources',{exact:true}).click();await page.locator('[data-live-setting=output]').selectOption('landscape');const popup=context.waitForEvent('page');await page.locator('[data-live=output-window]').click();const audience=await popup;await audience.waitForFunction(()=>window.__GAMMA_READY__);const cdp=await context.newCDPSession(audience),win=await cdp.send('Browser.getWindowForTarget');await cdp.send('Browser.setWindowBounds',{windowId:win.windowId,bounds:{width:1920,height:1080}});await audience.setViewportSize({width:1920,height:1080});await page.bringToFront();await page.locator('[data-live=source]').click();await expect.poll(()=>page.evaluate(()=>__gammaStudio.snapshot().screen)).toBe(true);const source=await page.evaluate(()=>__gammaStudio.snapshot().sourceSettings);expect(source.width).toBeGreaterThanOrEqual(1920);expect(source.height).toBeGreaterThanOrEqual(1080);await page.locator('[data-live=record]').click();await expect.poll(()=>page.evaluate(()=>__gammaStudio.snapshot().phase)).toBe('recording');
 const started=Date.now(),samples=[];let beat=0;while(Date.now()-started<seconds*1000){await page.waitForTimeout(Math.min(5000,seconds*1000-(Date.now()-started)));const snapshot=await page.evaluate(()=>({state:__gammaStudio.snapshot(),heap:performance.memory?.usedJSHeapSize||null}));expect(snapshot.state.phase).toBe('recording');samples.push({seconds:(Date.now()-started)/1000,...snapshot});await page.evaluate(i=>Reveal.slide(i),beat++%20);if(beat%6===0){await page.evaluate(()=>__gammaStudio.pause());await page.waitForTimeout(500);await page.evaluate(()=>__gammaStudio.pause());}if(beat%9===0){await audience.bringToFront();await page.waitForTimeout(400);await page.bringToFront();}if(beat%12===0)writeFileSync(join(evidence,'endurance-progress.json'),JSON.stringify({seconds:(Date.now()-started)/1000,samples:samples.length,last:snapshot},null,2));}
 await page.evaluate(()=>__gammaStudio.stop());await expect(page.getByTestId('studio-recording-review')).toBeVisible({timeout:30000});const take=await page.evaluate(async()=>{const list=await __gammaTakeStore.list();return list.find(t=>t.status==='complete');});writeFileSync(join(evidence,'endurance.mp4'),Buffer.alloc(0));await page.evaluate(async id=>{for await(const blob of __gammaTakeStore.chunks(id)){const r=await fetch('/__qa/export',{method:'POST',body:blob});if(!r.ok)throw Error('Export failed');}},take.id);const probe=JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-show_format','-of','json',join(evidence,'endurance.mp4')],{encoding:'utf8'}));expect(+probe.format.duration).toBeGreaterThan(seconds*.9);const video=probe.streams.find(s=>s.codec_type==='video');expect([video.width,video.height]).toEqual([1920,1080]);for(const time of [1,Math.floor(seconds/2),Math.floor(+probe.format.duration)-2])execFileSync('ffmpeg',['-v','error','-y','-ss',String(time),'-i',join(evidence,'endurance.mp4'),'-frames:v','1',join(evidence,'endurance-'+time+'.png')]);writeFileSync(join(evidence,'endurance-proof.json'),JSON.stringify({source,seconds,take,samples,probe,syntheticCameraAndMicrophone:true,realTabCapture:true},null,2));
 }finally{await context.close();rmSync(profile,{recursive:true,force:true});}
});
